### ISSUE TITLE
Stream latency info on channel page and/or player overlay

### ISSUE THREAD

**Issue by fbck** [FrankerFaceZ/FrankerFaceZ#1060]
It'd be useful to have Latency to Broadcaster value be shown somewhere where it would be just visible, without having to click a bunch of buttons to look it up. Currently, it takes several clicks to see the latency, and the Video Stats overlay has too much extraneous information, so it's inconvenient to leave it open.

The most convenient places for latency value would be next to viewer count and stream uptime in regular page mode, and somewhere on the player's overlay in theater mode and fullscreen mode - maybe at the top, next to Live badge, or down below next to player buttons.

I've seen mentions of this in other issues about stream latency display for mod views, but this feature would be useful for any stream, not just the ones where you have the mod capability. It's a valuable bit of information for any interactive stream.

**Comment by SirStendec** [comment]
Already a feature.

Channel > Metadata. Playback Statistics.

**Comment by fbck** [comment]
There's no visible delay info in Theater mode or Fullscreen mode.

**Comment by barbedknot** [comment]
I only found out this was a feature by googling "twitch "video stats" shortcut", which led me to this issue. Does whoever named this feature "Playback Statistics" not understand that on twitch it's called "Video Stats", so logically every user will search that terminology in the ffz "Control Center", find nothing, then give up until they're annoyed enough to look for a different solution? Because that was exactly my process. Please add the "Video Stats" terminology in some form to the "Playback Statistics" feature, if you insist on preserving the removed-from-practice terminology of "Playback Statistics".

Also, I'm noticing that when the latency is too great, it displays that the playback is sped up. This made me search "speed" in the ffz "Control Center" to find Player > General >"Allow the player to speed up to reduce delay". Judging by the description, this appears to be behaviour exhibited by twitch itself, only, now ffz is showing me when it's happening. Will you please provide the tools to speed up video within twitch at my own choosing? I realize there are browser extensions that do this already. But it would be nice. Especially if it sped up ads as well. Which I have observed browser extensions having the ability to do, on twitch.
