### ISSUE TITLE
Metadata - Not displaying in Mod-View anymore

### ISSUE THREAD

**Issue by SebVFX** [FrankerFaceZ/FrankerFaceZ#1099]
I noticed that metadata is not displayed in Mod-View anymore. Most important the latency.

**Comment by jschadewald** [comment]
I have this same issue since updating Chrome to Version 92.0.4515.131 (Official Build) (64-bit)
I'm using FrankerFaceZ extension Version 1.57
I don't this this is relevant to the issue, but I'm also using The FFZ Add-On Pack Version 3.1.2

Details:
The feature in the FrankerFacez dialog under Channel > Metadata, enabled as "Playback Statistics," still correctly displays in the standard Twitch interface, but is no longer visible in Twitch's Mod View. Specifically, I don't see the Stream Latency icon or the value of the latency next to the viewer count when I'm in Mod View for a channel (tested on two different channels).
