### ISSUE TITLE
Preventing IP address leaking

### ISSUE THREAD

**Issue by fbck** [FrankerFaceZ/FrankerFaceZ#1104]
There has been a lot of concern around IP address leaking.
Some malicious extensions have been used to get people's IP addresses and harass them over it. 
Good rundown of it has been written here in this comment: https://www.reddit.com/r/Twitch/comments/oth99x/twitch_description_ip_grabber/h76g9m4/?utm_source=reddit&utm_medium=web2x&context=3

What options are there currently in FFZ that could help prevent this? 
There is a setting for "Show overlay extensions", but that just hides extensions, and the overlay extensions specifically, without preventing them from loading (I suppose). While it does just what it says, it still could be taken in a wrong way, leading people to believe that this offers some kind of protection, when it just doesn't.
Could those options be made clearer? As in, have a description that would inform people that some option would help protect them, and have options surface when searching by 'ip address' or something of the sort.
What options could be implemented? 
For instance, disabling ALL of twitch extensions might be inconvenient and too drastic, as there are many extensions that are trusted by people and have been secure in this regard. But an option to prevent less known extensions from being loaded, or certain extensions that utilize personal data specifically, could be helpful. Like a blacklist/whitelist, or some kind of rule that would prevent resources being loaded from hosts that aren't twitch and that could be logged by third parties.

**Comment by SirStendec** [comment]
I will not be implementing anything into FrankerFaceZ with the intention of blocking extensions from loading, as doing so would provide users with a false sense of security.

FrankerFaceZ does not run in an elevated security context, so it is not possible for FrankerFaceZ to block content from loading like an ad-blocker. We need to work inside the system. Could I modify the Twitch app so that it doesn't try to load an extension? Yes. But it would be brittle and prone to break when Twitch releases an update. It would be unreliable and not prevent extensions from loading on the first page load.

Commander Root has released an extension for blocking Twitch Extensions, and I would direct users to use that. It blocks network requests directly. Links to that for various browsers here: https://twitch-tools.rootonline.de/disable_twitch_extensions.php


As for the description of the Show Overlay Extensions setting, I see a point about making it clear with a description that the extensions are still loaded and just not visible to the user. I'll add that in a future update. Leaving this open until I do.

**Comment by SirStendec** [comment]
Added a notice in a529e7fd279757393b9500b4d59ec28d96d4b1db so I'm closing this.
