### ISSUE TITLE
7TV emotes look smaller

### ISSUE THREAD

**Issue by mopoIo** [FrankerFaceZ/FrankerFaceZ#1171]
**Describe the bug**
7TV look smaller than FFZ/BTTV emotes.

**To Reproduce**
1. Enable 7TV add-on.
2. Send a 7TV emote.

**Expected behavior**
All emotes should look the same size.

**Screenshots**
[Screenshot](https://cdn.discordapp.com/attachments/682764268546162704/939448762198269972/unknown.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Other Extensions: [Adblock Plus]

**Comment by mopoIo** [comment]
I only use FrankerFaceZ, a friend uses BTTV and 7TV (without frankerfacez) and they look the same size for her

**Comment by SirStendec** [comment]
AFAIK, 7tv has had an issue with their CDN where they were resizing images incorrectly based on a faulty assumption about how browsers handle high-dpi images. Not a hard one to make, since Twitch was doing the same for a long time.

I'm not sure what their progress is on fixing the problem, but it's something they need to handle. Either in their service or via an update to the FFZ add-on they maintain.

Either way, it's not an FFZ issue.
