### ISSUE TITLE
Emote size & preview problem

### ISSUE THREAD

**Issue by Bucketsmith** [FrankerFaceZ/FrankerFaceZ#1223]
**Describe the bug**
Some emotes stay small size, despite setting larger size option.
Also, emote preview doesn't seem to be working for some emotes.

**To Reproduce**
Use any emote in chat.
See that they are small, others are large.
Hovering over them shows a "broken image" icon and no info.

**Expected behavior**
To see emotes in larger size as per the setting.
And to see the hover menu give information and show the emote.

**Screenshots**
![image](https://user-images.githubusercontent.com/20886583/171963779-9ab24de1-a5ab-45ea-8a13-cf093f4d6f86.png)
![image](https://user-images.githubusercontent.com/20886583/171964000-e8fae4c1-9bce-43ca-8c79-9b8957e0bd18.png)

**Environment (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 101.0
 - Other Extensions: BTTV, 7TV, 

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://pastebin.com/51UCRTLR

**Comment by SirStendec** [comment]
BetterTTV and SevenTv both affect chat rendering in their own ways, and either or both may be responsible for some FFZ features failing to work correctly.

This is especially relevant as if, for example, an emote is injected into the chat line by one of those extensions rather than FFZ that emote wouldn't be made larger by FFZ because FFZ has nothing to do with it.

I don't plan on going out of my way to broaden compatibility for this specific situation, as FrankerFaceZ is capable of displaying emotes from both of those extensions using its add-ons system.

**Comment by Bucketsmith** [comment]
I even had this issue when the other plugins were disabled. I don't know enough about browser plugins, would that still be able to interfere then?
