### ISSUE TITLE
[Feature Request] Support newer emoji

### ISSUE THREAD

**Issue by GreyAsteroid** [FrankerFaceZ/FrankerFaceZ#123]
**Bug / Idea**: FFZ does not recognize emoji from the Unicode 8 and 9 releases. This means that the emoji list does not contain these emoji and you cannot tab complete these emoji when typing them in. 

This directly affects my ability to input thinking face emoji in a timely fashion. 
Please consider supporting newer emoji.

**Comment by SirStendec** [comment]
I'm guessing you have FrankerFaceZ set to use Noto images for emoji? Unfortunately, the repository for that ([googlei18n/noto-emoji](https://github.com/googlei18n/noto-emoji)) is hilariously out of date when it comes to SVG-formatted images. FFZ currently uses SVGs for emoji rather than providing multiple sizes of PNGs, so that's an issue.

You have a point about not supporting Unicode 9 releases though, and I've just updated the data files for that.

As a result, FFZ now supports 1,774 emoji from One and Twemoji... and 856 from Noto.
