### ISSUE TITLE
(Bug) Unable to access FFZ menu as well as Twitch Chat

### ISSUE THREAD

**Issue by AnonymousJr** [FrankerFaceZ/FrankerFaceZ#129]
**Web Browser**: Firefox

**Do you use BetterTTV or other Twitch extensions**: BTTV Installed, but disabled

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: Unable to access

**Bug / Idea**: A setting combination can leave you unable to access chat as well as FFZ settings menu.
![Screenshot](https://i.imgur.com/MKRGTAn.jpg)

**Steps to Reproduce (if Applicable)**: Easily replicated, but am unable to reset FFZ settings to do so.

**Comment by AnonymousJr** [comment]
Turning on theatre mode allows access to chat and FFZ Menu.

Settings reset, going to try and recreate.

**Comment by AnonymousJr** [comment]
Steps to recreate:

Settings > Advanced > Change following settings:

- Channel Bar on Bottom > On top, either setting.

- Minimal Channel Bar > Always On (Video Below)


Log for prosperity's sake:  http://putco.de/NTc0OA.log

**Comment by SirStendec** [comment]
So, what you enabled is Portrait Mode, which puts the chat above or below the video. When that's set to Automatic, it only uses that layout when the window is taller than it is wide. When it's set to Always On, it always uses portrait mode.

The problem is that chat automatically hides itself when there's not enough room. With portrait mode disabled, make a window narrow enough and you'll see it happen. The same thing applies to chat in portrait mode, but it's a matter of the window not being tall enough.

When this happens, you need to either make your window narrower till chat appears, or open your dashboard and access settings there to disable it.

Yes, this isn't really an optimal solution. There *is* a popup when you're using portrait mode and it hides chat though. (At least, there's supposed to be. I suppose that might be broken...)

Also, settings are no longer attached to chat in the rewrite of FrankerFaceZ that I am working on, so the whole situation becomes a non-issue then.
