### ISSUE TITLE
7TV tab completion is broken while Room Actions are displayed above the chat input box

### ISSUE THREAD

**Issue by slydolphin** [FrankerFaceZ/FrankerFaceZ#1294]
Chat > Actions > Room Settings 
Display Room Actions above the chat input box

7TV tab completion is broken while Room Actions are displayed above the chat input box.
Enabling said option causes 7TV emotes not be able to be "tab completed".

Browser: Chrome
Windows 10
Other extensions: BTTV, 7TV

**Comment by SirStendec** [comment]
That feature has existed since before 7tv existed and has not changed. I don't consider it something for FrankerFaceZ to fix.

BetterTTV has had a similar issue in the past where they were not properly reapplying modifications when the chat input element re-rendered. I assume 7tv has to fix that same issue.
