### ISSUE TITLE
Audio compression greyed out and not working

### ISSUE THREAD

**Issue by ItsChicobo** [FrankerFaceZ/FrankerFaceZ#1305]
**Describe the bug**
Audio compression is greyed out on streams. It claims that it can't be enabled for clips, even on a currently live stream's homepage. Refreshing the page and resetting the browser or even the computer does not seem to restore functionality.

**Screenshots**
See below.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version: 108.0.5359.99 (Official Build) (64-bit)
 - Other Extensions: BTTV plugin, 7tv plugin, uBlock Origin

I tried to upload the log but it seems to hang on 'Uploading...' when I click the button. So I pasted the whole log in a .txt file, attached here.
[ffzlog.txt](https://github.com/FrankerFaceZ/FrankerFaceZ/files/10198632/ffzlog.txt)

![image](https://user-images.githubusercontent.com/120225938/206808477-e10ab893-6f45-45db-bc4c-c7bb0ab24922.png)

**Comment by OndrejSuperman** [comment]
Same problem

**Comment by CuraeL** [comment]
Same issue. Seems like there's already a commit that fixes it. Would be great to get merged.

**Comment by Heydran** [comment]
same proble, using brave

**Comment by melutzke** [comment]
Devs take weekends too, but this should get fixed in the next couple days :) .

If you want a workaround, open your chrome (or brave) dev console and paste this little snippet of code, then hit enter:

`this.FrankerFaceZ.instance.__modules["site.player"].canCompress = () => true`

You will need to do it each time you open a stream, but this overrides the canCompress check forcing it to reply true without really checking if valid or not.

**Comment by CuraeL** [comment]
That worked wonders. Thanks a bunch! :) Will just have to do that on each stream load. No biggie!

**Comment by SirStendec** [comment]
Fixed as of 4001d15b188364dbd68c7e4e87930e6ff154a5ba
