### ISSUE TITLE
7TV Compatibility

### ISSUE THREAD

**Issue by CrazyWolf13** [FrankerFaceZ/FrankerFaceZ#1349]
**Describe the bug**
7TV 3.0.1 won't work with FFZ

**To Reproduce**
1. Activate 7TV extension
2. Any Chat related stuff will not work.

**Expected behavior**
Better integration so FFZ and 7TV can work together instead of against each other. 

**Environment (please complete the following information):**
 - OS: Win11
 - Browser Opera GX (Chromium)
 - Version LVL4 (core: 96.0.4693.117)
 - Other Extensions: FFZ, FFZ-Addons, 7TV

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
Due to the internal uploading feature not working I provide it with pastebin and a password:
PW:VStp8nZGAp
https://pastebin.com/x76rp1mn

**Comment by SirStendec** [comment]
> **TL;DR:** 7TV needs to fix their chat. This is not a BTTV/FFZ issue. For now, consider using the 7TV add-on for FFZ instead of the 7TV browser extension.


With their recent v3 update, 7TV has implemented a complete replacement of chat instead of building on top of the existing Twitch chat like FrankerFaceZ and BetterTTV do.

As a result, features from FrankerFaceZ and BetterTTV do not work with this chat replacement.

As a result, implementing support for 7TV's chat would effectively double the work we would have to do for most chat-related features.

At this time I have no plans to go out of my way to support 7TV's chat replacement. Support should be implemented from 7TV's side.

The lead developer tells me that they plan on introducing an API for customizing the rendering of chat. When that is actually stable and available, I will reevaluate supporting some chat features for users with the 7TV extension installed.

Until that time, it is simply infeasible. I am not happy with our users having issues, but short of going out of my way to break 7TV so that their chat replacement doesn't function, there is not enough time in my day to fix everything.

---

For users that prefer the chat experience with FrankerFaceZ and/or BetterTTV, I would suggest that you simply do not use the 7TV browser extension at this time.

FrankerFaceZ has support for 7TV's emotes, badges, cosmetics, and other content via the 7TV Emotes add-on you can enable in the FFZ Control Center (along with a lot of other interesting add-ons).

BetterTTV has support for 7TV's emotes that can be enabled from within that extension's settings.

**Comment by CrazyWolf13** [comment]
I can understand that.
Thank for the explanation and i won't use the extension because it lacks so many features, on the other side until now i could double post messages without getting  the message: duplicate message.
