### ISSUE TITLE
API: List All Image Sizes

### ISSUE THREAD

**Issue by RealityRipple** [FrankerFaceZ/FrankerFaceZ#1363]
The current API lists the sizes of the 1x pixel density images for emotes, which assumes that all other sizes for a given emote are identically scaled. However, some emotes have different sizes for one or both of the 2x and 4x pixel density images, resulting in bad scaling math. This can be seen live in the extension by trying to enter one of these emotes <https://www.frankerfacez.com/emoticon/688652> and <https://www.frankerfacez.com/emoticon/688653> in the "send" box emote preview (you can test on my channel without adding them if you want; same username). It also prevents third-party tools from knowing the true dimensions of 2x and 4x images without loading the relevant image first.

Personally, I suggest a non-breaking `width2` `height2`, `width4` `height4` property set, rather than turning `width` and `height` into arrays or making subgroups. I also suggest not starting with a number, for JavaScript property name's sake. You could also only include this data if there is a discrepancy between pixel densities.

**Comment by SirStendec** [comment]
Emotes only have one size. If the high resolution images are not multiples of that size, then the emote was incorrectly submitted.

In this example, both of the emotes you linked as examples are incorrectly formatted. I've manually fixed them, rather than forcing you to resubmit them.

The new emote uploader added when we added support for animated emotes prevents this from being an issue for all emotes going forward, but there may be other incorrectly formatted emotes in the library. The correct way to handle this is assuming the size provided by the API is correct and ignoring the size of the image.
