### ISSUE TITLE
Chat tooltips don't work

### ISSUE THREAD

**Issue by ghost** [FrankerFaceZ/FrankerFaceZ#15]
**Web Browser**:
Firefox 49.0.1

**Do you use BetterTTV or other Twitch extensions**:
BTTV4FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
I get 'There was an error uploading the FrankerFaceZ logs' when clicking on Logs link

**Bug / Idea**:
The setting under Advanced, 'Link Information Beta' doesn't show tooltips over shortened youtu.be links.

**Steps to Reproduce (if Applicable)**: 
Toggle setting ON and wait for someone to paste some links and then hover over it and it shows nothing.

**Comment by LawlyPopz** [comment]
Yup doesnt seem to do anything at all

![I Second This](http://pushzz.xyz/img/e8dcc.png)

**Comment by SirStendec** [comment]
This is actually a problem with the servers rather than the client. It worked quite a long time ago, but our user base quickly outgrew my server's capacity and I just haven't gotten around to writing a new backend for the feature that scales well.

I'll leave this bug open. Maybe it'll finally motivate me to code the dumb backend already.
