### ISSUE TITLE
[Bug] Font for room state goes funny if R9K, Follow, Sub and Slow mode are all enabled.

### ISSUE THREAD

**Issue by jnki** [FrankerFaceZ/FrankerFaceZ#150]
**Web Browser**: Vivaldi/Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ:AP Script, Twitch Giveawys, Twitch Now.

**Bug**:
The room state font goes a bit strange if R9K, Follow, Sub, and Slow mode are all enabled at the same time.

![image](https://cloud.githubusercontent.com/assets/17442109/25560041/040ee3ee-2d41-11e7-82bc-d64209eacc99.png)

**Steps to Reproduce (if Applicable)**:
Enable Sub, Follow, R9K and Slow mode

**Comment by SirStendec** [comment]
Yeah, it's a bit screwy. It's intentional though. When you have enough visible state indicators, the font does that in an attempt to take up slightly less room.

Really, I just need to get someone to make icons for the states, or otherwise figure out a better way to show them all at once. I don't like it how it is now.

Still, it's intentional.
