### ISSUE TITLE
Costum moderation hotkeys/ double click name 

### ISSUE THREAD

**Issue by SpAToSMG** [FrankerFaceZ/FrankerFaceZ#153]
**Idea**

Costum moderation hotkeys!?!?!?!?
Why isn't this a thing yet. Yes using T to TO somebody is nice and quick but a lot of the times 10 minutes is just to much. Would like to get a feature to costumly set those sorts of hotkeys for the duration the mod wants for the most effective moderation of a chat.

Like there is on the moderation card (Moderation Card Additional Buttons) where you can put your costum command on the card just wanna see the same with hotkeys.

Double click a name and it shows up automatically in the chatbox like BTTV has it. 
Just nice quick and should be easy to implement

First time using FFZ and those are my ideas to really give it a further edge over BTTV 

EDIT: just noticed the mod card doesn't close when you click outside of it?
is there a fix for that?

**Comment by SirStendec** [comment]
Custom hotkeys are planned for FrankerFaceZ's v4 rewrite. I haven't put them in thus far because the settings UI really doesn't have an answer for configuring them in a reasonable, sane, intuitive way.

Double clicking a name isn't quite so easy as you think, and I'm not implementing it as it would make every single other thing that involves clicking in chat feel laggier with how chat input handlers are designed. Might change in v4, I don't know yet. It's still to early to say.

There's no way to make moderation cards close automatically. If you have one focused and hotkeys enabled, you can close it with Escape. Otherwise, click the X, or just leave it open and it will be replaced when you click on another user.

Closing this since it's basic v4 stuff and already on my to-do list.

**Comment by SpAToSMG** [comment]
sweet thanks
