### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by Antzer** [FrankerFaceZ/FrankerFaceZ#156]
**Bug / Idea**:
BTTV recently confirmed they wouldn't be putting desktop notifications back in their extension which i find ridiculous because twitch's own system is only valid when you have their webpage open and also has no sound, Not really an idea but i would really love if this extension ventured into this.
Thanks for reading.

**Comment by SirStendec** [comment]
As you've said, the current system only works when you have the webpage open. If I added it to FrankerFaceZ, you'd encounter the same issue. Rather than adding a poor implementation to FFZ, I'd suggest that you get an extension like Twitch Now.

That way, you'll be notified of channels going live whenever your browser is open, whether you're on Twitch at the time or not.
