### ISSUE TITLE
Extension stopped working completely

### ISSUE THREAD

**Issue by jigsaw3xD** [FrankerFaceZ/FrankerFaceZ#1565]
**Describe the bug**
All of a sudden the extension stopped working completely, no FFZ Control Center button or any effects. Couple of days ago everything was fine. I've reinstalled it (from the Chrome Web Store), turned off other extensions that affect twitch (AdGuard and BTTV), tried incognito mode but that didn't work.

**Environment (please complete the following information):**
 - OS: Windows 10 19042.1620
 - Vivaldi
 - Newest, 6.9.3447.54

**Comment by Kanawanagasaki** [comment]
Do not work on firefox as well

**Comment by SirStendec** [comment]
Are you connecting from Russia? I'm still investigating but reports are that FFZ's website is being blocked in Russia.

You can try using this version of the Chrome extension in the meantime, which doesn't require access to the FFZ website to load: https://chromewebstore.google.com/detail/frankerfacez-nightly/jgnjpfcdneiofkjkidlokfipfaignogj

**Comment by REWesker** [comment]
**Note:** this is more for those who are in Russia and come here searching answers.

Can confirm that FFZ cdn subdomain got blocked in Russia on October 18. This is because of 7 emote pages (some of which are duplicates because they are different sizes) that should be individually blocked without affecting the rest of the site, but ISPs usually block full access to domain and/or IP.

<details>
<summary>Details of blocking</summary>
IPs affected:
188.114.98.233
188.114.99.233
2a06:98c1:3122:e000::9
2a06:98c1:3123:e000::9 

Emote pages in question:
https://cdn.frankerfacez.com/emoticon/599580/4
https://cdn.frankerfacez.com/emoticon/298316/2
https://cdn.frankerfacez.com/emoticon/569357/2
https://cdn.frankerfacez.com/emoticon/569357/4
https://cdn.frankerfacez.com/emoticon/594031/4
https://cdn.frankerfacez.com/emoticon/461597/4
https://cdn.frankerfacez.com/emoticon/461597/2

Yes, whole subdomain got nuked in Russia because of gay memes
</details>

**Comment by AlexWayfer** [comment]
> Yes, whole subdomain got nuked in Russia because of gay memes

It's weird that I can load these `cdn.` emotes (without VPN), but the extension is not loading.

**Comment by Pazuzu777** [comment]
> Are you connecting from Russia? I'm still investigating but reports are that FFZ's website is being blocked in Russia.
> 
> You can try using this version of the Chrome extension in the meantime, which doesn't require access to the FFZ website to load: https://chromewebstore.google.com/detail/frankerfacez-nightly/jgnjpfcdneiofkjkidlokfipfaignogj

this one doesn't work for me either

**Comment by ExpandingShapes** [comment]
Same. Also connecting from Russia.
Yesterday the extension stopped working completely. FFZ script installed with Tampermonkey on Firefox to be precise. 
I can load FFZ website and half of the emotes mentioned above but not the script on the website.
Yes, Chrome extension still works but now I can't use FFZ with my favorite browser. 
I'm going to try unblocking FFZ CDNs with zapret (software for bypassing DPI blocks)

**Comment by AlexWayfer** [comment]
I guess users from Russia should use VPN or other methods, and extensions like 7TV of FFZ can't do anything with it.

**Comment by iamRESOLUTION** [comment]
add cdn.frankerfacez.com to goodbye filters and ffz will work

**Comment by jigsaw3xD** [comment]
> Are you connecting from Russia? I'm still investigating but reports are that FFZ's website is being blocked in Russia.

Yes, I'm from RU, tho FFZ's website is working fine for me.

> add cdn.frankerfacez.com to goodbye filters and ffz will work

Thanks, this worked! 

Sorry for creating a bug report with an issue on my end. I'd've figure it out myself but weirdly our news sites reported the block as block of 7TV emotes (with most of 7TV emotes still working) so I had no idea that FFZ was affected as well.

**Comment by AlexWayfer** [comment]
> but weirdly our news sites reported the block as block of 7TV emotes (with most of 7TV emotes still working) so I had no idea that FFZ was affected as well.

7TV has been blocked a few days ago. And their emotes can work because they're distributing from another domain (CDN), as I understand. Anyway, some Russian providers can block this emotes-CDN too.

FFZ has been blocked yesterday. I guess there are not a lot of news about it yet.

**Comment by NikSavchenk0** [comment]
@REWesker, how you got this information?
