### ISSUE TITLE
[Feature Request] Userscript mirror

### ISSUE THREAD

**Issue by Dum4G** [FrankerFaceZ/FrankerFaceZ#1567]
**Is your feature request related to a problem? Please describe.**
What a world to live in. It turns out your private domain may be banned in entirety by government just because they didn't like a single emote. In other words https://cdn.frankerfacez.com/script/ffz_injector.user.js is no longer accessible in Russia.

**Describe the solution you'd like**
I'd like FFZ scripts to be hosted on some global infrastructure like Github pages which are painful to be banned. At least, give us an option to synchronize the script from self-hosted mirrors or to cache a script if possible, so an entire extension couldn't be broken within a day

**Describe alternatives you've considered**
I have checked and it works with a VPN. Not suitable for vieweing Twitch itself tho.

**Comment by SirStendec** [comment]
This problem is effectively solved by the manifest v3 version of FrankerFaceZ, which bundles the necessary scripts. This is currently accessible as [FrankerFaceZ Nightly](https://chromewebstore.google.com/detail/frankerfacez-nightly/jgnjpfcdneiofkjkidlokfipfaignogj) on Chrome, and will be accessible as the main extension soon.

I've also submitted it to Firefox but they take 7+ days every time to come up with some new trivial reason to reject it related to them fucking up the build process, so I wouldn't hold out on that showing up there any time soon.

Built copies of the extension can also be downloaded from the [FrankerFaceZ/Extension](https://github.com/FrankerFaceZ/Extension/actions) repository, which does a new build any time there's been a commit to either this repo or the add-ons repo. Those just need to be loaded into a browser using developer options.

Finally, I've also made a `cdn2.frankerfacez.com` which is only used for serving script files. This should, with luck, avoid the domain being blocked because of emote content in the future and causing issues.

**Comment by qzmtch** [comment]
> Finally, I've also made a `cdn2.frankerfacez.com` which is only used for serving script files. This should, with luck, avoid the domain being blocked because of emote content in the future and causing issues.

It looks like frankerfacez.com is completely blocked in Russia, not just cdn
