### ISSUE TITLE
Scrollback Length 7tv Override/Profile Prioritization Issue

### ISSUE THREAD

**Issue by agenttylo** [FrankerFaceZ/FrankerFaceZ#1579]
Description:
I've noticed a recurring issue where an added profile randomly takes priority over default settings, blocking the configurations I have in place. This issue seems inconsistent, making it difficult to find a reliable, quick fix. I've identified that disabling FrankerFaceZ (FFZ) resolves the issue temporarily, suggesting that the interaction with FFZ might be part of the problem.

Expected Behavior:
default profiles should not override default configurations, and settings priority should remain with the user-specified default unless manually adjusted.

Additional Information:

7TV settings are currently set to the FFZ default of 150.
Disabling FFZ temporarily resolves the issue.
Redownloading FFZ & 7TV temporarily resolves the issue.

**Comment by SirStendec** [comment]
It sounds like you're using the 7TV browser extension rather than the add-on. As far as I know, that specifically introduces a settings profile to FFZ to adjust settings for compatibility. If it causes problems, that's really something for the 7TV devs to deal with since its their settings profile that they're adding using FFZ's API.

That is working as intended.
