### ISSUE TITLE
Stream Uptime Broken/Missing on Channel Cards

### ISSUE THREAD

**Issue by DatXFire** [FrankerFaceZ/FrankerFaceZ#1590]
**Describe the bug**
Stream uptime is missing on channel cards despite the option being enabled.

**To Reproduce**
1. Go to a directory with channel cards, such as following, or a category.
2. See that uptime is not present on any channel cards.

**Expected behavior**
Stream uptime is displayed on channel cards.

**Screenshots**
https://i.imgur.com/dmPiMQ7.png
https://i.imgur.com/jZMIpIO.jpeg

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 133.0 (64-Bit)
 - Other Extensions: BTTV, uBlock Origin, Disable Twitch extensions (Uptime still does not appear with these extensions disabled.)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://logs.frankerfacez.com/6d03d838-24c8-47ab-8b32-299cec9ed9d1

**Additional context**
Screenshot showing option is enabled: https://i.imgur.com/3Oweoaz.png

**Comment by SirStendec** [comment]
This was already fixed in version 4.76.0. Mozilla is exceptionally slow at approving updates to add-ons so you probably won't see it till next week. There is nothing I can personally do about that. If you want to get the latest FFZ builds faster, consider switching to the user script instead of the browser extension.
