### ISSUE TITLE
Audio Compressor wont work when you block ffz ip

### ISSUE THREAD

**Issue by akoolud** [FrankerFaceZ/FrankerFaceZ#1591]
I'm sure this is not intentional but audio compressor doesnt work If I block the malicious requests to ffz.

I see no reason for ffz to make extra calls except for emote list and emotes 
but for some reason ffz retrieves a list of useless crap thats never gonna be used and on top of that audio compressor for some reason needs this malicious list to be retrieved?

I can probably fix this on my side but it will be nice for ffz not try to be worst that twitch and send extra crap everyone blocks/turns off.

**Comment by SirStendec** [comment]
Assuming you're using the manifest v3 extension that bundles FFZ, the compressor works fine if FFZ's domain is blocked.

If you're using the user script, then of course it wouldn't work if you block FFZ's domain since it needs to load the scripts from FFZ's domain.

None of the requests are malicious.

If you had questions about a specific request, I could explain why it was being made, but you're just here to be insulting. As I said in the other issue: kindly fuck off.
