### ISSUE TITLE
FFZ for older version of browsers

### ISSUE THREAD

**Issue by akoolud** [FrankerFaceZ/FrankerFaceZ#1592]
**Is your feature request related to a problem? Please describe.**
Add a release to be able to manually install on older version of browsers (before cancer AI) atleast~3 years ago (Chrome/Brave)

**Describe the solution you'd like**
Ive seen 0 things change in ffz since 8 years ago still works the same I dont see why its the only extension not working on downgraded browsers.

**Describe alternatives you've considered**

**Additional context**
If you didnt know older version of Brave before the cancer AI is 10x faster
even the opening a new blank tab page is much more faster!
it will be nice to have ffz without the extra crap for some reason you added that I never used or seen

**Comment by SirStendec** [comment]
FrankerFaceZ targets ES2020. Any browser build from the second half of 2020 should work. I'm not sure when the relevant browser would have added support for manifest v3, but that was introduced in Chromium prior to 2020 afaik so that shouldn't be a blocker for Chromium-based browsers. If it is, there's always the user script version.

If you actually provided details on what wasn't working I could probably assist you.

However, you seem to be here just to call my work stagnant, malicious crap. So kindly fuck off.
