### ISSUE TITLE
[Feature request] Missing the "Permit Button" and other Stuff/Ideas

### ISSUE THREAD

**Issue by Kraenky** [FrankerFaceZ/FrankerFaceZ#165]
Hey, i have a small Question...
I've been using, BTTV and FrankerFace and had the Setting: Disable BTTV Mod Cards
on. Now looks like better, but you forget the Button to give other Persons a Link Permission :). (Like BTTV) 
I hope you can Add this? 
Would be nice.

Thank you.

Greetz

PS: And a good Idea is: Doubleclick on the Nick to Copy the Nick in the Chat... (like BTTV) "@NICK"... (That not working anymore when you Enable the Option: Disable BTTV Mod Cards")
And a other Idea is: Do other People market a Personal Text, then give the chat the Feedback in Red... (Is the same like @NICK ...You got a Red Message in Chat... That would be nice to Create a Own Text who the People market it. (The Problem is, Other Nicks are to Long, and guys write only a little bit from the Full Name, so we can Add a Text from the Nick and get nevertheless the Red Message as we have the Full Nick writing.

I hope you know what i Mean.
Sorry i'm from Germany, my English is not Perfekt xD.

**Comment by SirStendec** [comment]
You can add a permit button yourself using the Moderation Card Additional Buttons setting. You can also add them to chat lines with custom in-line mod icons. I'm not going to make !permit a default button because not everyone uses a bot with that command.

Double-click for chat is not feasible with how chat input is currently implemented.

As for highlighting things in red, you can set custom words that are highlighted in chat with the Highlight Keywords setting. To show lines in red with highlighted words, you can use the Chat Line Backgrounds setting.
