### ISSUE TITLE
Metadata still not working for hosted channels!

### ISSUE THREAD

**Issue by iiNinetales** [FrankerFaceZ/FrankerFaceZ#19]
**Web Browser**: 
Chrome

**Do you use BetterTTV or other Twitch extensions**: 
BTTV4FFZ

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**:
Metadata still not working for hosted channels!

**Steps to Reproduce (if Applicable)**:
View any channel that is hosting someone1

**Comment by RedSnt** [comment]
I'm not sure what type of metadata you want, because due to the new way twitch implements hosting all you can get now is the technical stuff like resolution, fps and latency and not practical stuff like viewer count and stream uptime.

**Comment by SirStendec** [comment]
This doesn't entirely accurately describe the problem. It's not a matter of working. Because it's Working As Intended (TM). As RedSnt comments, Twitch's redesign doesn't display stats like the viewer count. This isn't something FFZ has managed in the past. It's always been Twitch. And now they decided that information isn't necessary, I guess.

I hate the new design, and I do plan on taking action to do *something* to hosts, but I haven't decided on the best course of action yet.
