### ISSUE TITLE
Free With Prime pop-up hidden when sidebars are swapped

### ISSUE THREAD

**Issue by zuzuvelas** [FrankerFaceZ/FrankerFaceZ#2]
Similar to how the new subscribe pop-up _was_ being drawn off the screen, the "Free With Prime" pop-up also gets drawn off the screen to the right when the sidebars are swapped.

**Comment by SirStendec** [comment]
Rather than just offsetting this with CSS, I should really figure out how to hook all their new pop-ups. They seem to use https://github.com/yapplabs/ember-tether for positioning, and it seems rather unfortunately unflexible.

This'll go unfixed for a while, as a low priority since you can un-swap the bars to see it and it's not a major part of typical use of the website.

**Comment by SirStendec** [comment]
No longer valid due to Twitch design changes.
