### ISSUE TITLE
Work with the new Twitch desktop client

### ISSUE THREAD

**Issue by prasoc** [FrankerFaceZ/FrankerFaceZ#218]
The new Twitch desktop client is based on Electron so "can" use Chrome extensions, or if needed, use an embedded script within the client. 

I downloaded the .user.js script from the main site and ran the "ffz_init" JS function from within the desktop client's developer console. It surprisingly grabs the Twitch client, but then is unable to proceed due to being unable to find the chat div (there's a huge layout change with this new player).

I will try to get a modified FFZ to understand the new layout changes so that we can use FFZ in the desktop client - it definitely seems possible!

**Comment by prasoc** [comment]
There's an issue with FFZ being dependent on Ember: the new desktop client doesn't use Ember at all

**Comment by SirStendec** [comment]
Yes, I am very well aware of that. Twitch's desktop client, as well as their new website re-design, are both powered by React.

Unfortunately, FFZ in its current state is entirely dependent on Ember and how awesome Ember is in general. React is a closed up mess of a framework and the amount of work to get FFZ working on it is hilariously non-trivial.

I have already started work on a complete rewrite of FrankerFaceZ for the new website, and I'm hopeful that I'll be able to expand it to also function for the desktop client in the future. The new website is my first priority, of course.

No ETA, but hopefully the website extension will be ready by end of the month.

**Comment by prasoc** [comment]
Thanks, if you need someone to help with development of the rewrite then I am definitely willing to help

**Comment by Raziel-SSJ** [comment]
Hi.
I have a question about the Twitch desktop app, but first of all I have to mention that I have almost no knowledge in development.
I am able to load the extension by entering the "ffz_injector.user.js" script content in the console or by running a Snippet, but the manipulation and reload of preferences have to be done each time the application is launched.
Is there a way to automate this procedure or integrate the script or extension into the application so that it loads automatically and ensures that the preferences are kept?
Thanks a lot if anyone has a solution.
