### ISSUE TITLE
Clickable Mentions aren't rendered properly for users with a single digit in the name

### ISSUE THREAD

**Issue by Vivelin** [FrankerFaceZ/FrankerFaceZ#222]
**Web Browser**: Google Chrome (Version 60.0.3112.113 (Official Build) (64-bit))

**Do you use BetterTTV or other Twitch extensions**: FFZ Add-On Pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Mentions for a user with a number in the middle of the name don't look right. For example, sending a message that starts with `@c0ap` is rendered as `<span class="message"><span class="mentioning">@c0</span>ap `

I tested a bit more but I can't figure out the pattern. It works properly for `@a00aa`, but not for `@a0a`, `@a00a` and `@a0aa`. 

**Steps to Reproduce (if Applicable)**:
Turn on _Clickable Mentions_ and send a message that starts with `@a0a`. only the `@a0` part will be bold and the second `a` will appear separated. The example under **Bug / Idea** is for a real user, but the highlighting (bolding) will still be wrong for non-existent users.

**Comment by SirStendec** [comment]
This only applies to messages that you send yourself. If another person sends the message, you should see it with the name properly highlighted. This is because mentions in messages from other users are handled by FrankerFaceZ's `tokenize_users` function while mentions in messages from yourself are handled by Twitch's own `mentionizeMessage` function (which is a complete mess).

Twitch's mentionizeMessage function uses one of two regular expressions to grab mentions from the text, depending on whether or not you've send the message. If you haven't, it builds an expression including your username as: `new RegExp("@?\\b" + username + "\\b", "ig")`

That works fine. The problem is that if you did send the message, it uses this to highlight any mentions that you sent, and this doesn't work correctly: `/@(?:[a-z0-9]|[^\u0000-\u007F])(?:\w{4,25}|[^\u003A-\u007F\u0020-\u002F]{1,12})/gi`

That expression is overly broad and happy to match the shortest possible string. You can verify this behavior by sending a message with `@c0ap` in it without any extensions enabled:

![image](https://user-images.githubusercontent.com/14036657/29835394-d9cc8030-8cbf-11e7-9630-69234f3d1060.png)


This won't be an issue in FrankerFaceZ v4 as I'm rewriting chat in its entirety and not re-using any of Twitch's own code. No ETA on the release.
