### ISSUE TITLE
[Feature Request] Disable Prime loot and notifications

### ISSUE THREAD

**Issue by Zoooook** [FrankerFaceZ/FrankerFaceZ#224]
**Bug / Idea**:
Those red numbers are super annoying. Can we just remove them, or better yet, hide the icons entirely?

**Comment by SephirothWS** [comment]
![Image](https://i.imgur.com/5NmJHEZ.png) ... Going to bump this because I agree, the red numbers are super annoying, and no matter how many times I open it, the thing changes quite frequently so it shows up once again. ... As someone who cannot get prime because Amazon refuses to accept Paypal for Amazon Prime. ... >.>'

**Comment by SirStendec** [comment]
Implemented in dc358a774df0c8c3af69f375ffba6bc8ed7ef7ba
