### ISSUE TITLE
FFZ and BBTV cause twitch's darkmode to re-enable

### ISSUE THREAD

**Issue by thinkpad4** [FrankerFaceZ/FrankerFaceZ#244]
**Web Browser**:
Slimjet 14.0.16.0
**Do you use BetterTTV or other Twitch extensions**:
Yes both
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
I use FFZ and BTTV but use BTTV's darkmode, it seems that when FFZ and BTTV are on together with bttv's darkmode on twitch's darkmode keeps getting re-enabled with every visit of a new channel.

**Steps to Reproduce (if Applicable)**:

Seems to be only Slimjet that has the issue, but Slimjet is built on Chromium

**Comment by SirStendec** [comment]
FrankerFaceZ works fine with Twitch's native dark mode and, in fact, expects it to be on in order to have chat and a couple of other things look correct. Because of this, FFZ will itself enable Twitch's native dark theme whenever you enable FFZ's dark theme. FFZ restores the previous state of Twitch's native dark theme when you disable FFZ's dark theme. FFZ does not otherwise modify the state of Twitch's native dark theme.

To my knowledge, BetterTTV has not yet updated to support Twitch's native dark mode. If you're having appearance issues, it's likely due to BTTV.
