### ISSUE TITLE
Chat slow mode/timeout indicator (Enhancement)

### ISSUE THREAD

**Issue by sparcut** [FrankerFaceZ/FrankerFaceZ#260]
**Bug / Idea**:
Would be great to have a progress countdown circle, bar etc. to show when you can type again in chats in slow mode or after being timed out.

Adding a timeout progress indicator should be easy, not sure about chat timeout, prob stored in state. 

YouTube live has a similar feature that uses a circle progress bar and disables send message

**Comment by sparcut** [comment]
@SirStendec Sorry, how was this invalid?

**Comment by SirStendec** [comment]
This is already a feature. I haven't gotten around to adding it back to FFZv4 yet, not that that was a thing when this issue was opened, but it's definitely a feature of legacy chat. When chat is in slow mode and you send a message, or when you are timed out and try to talk, it displays a countdown on the chat button rather than the word `Chat`.
