### ISSUE TITLE
Chat username colours "pulsing" upon each new message(?)

### ISSUE THREAD

**Issue by hobblygobbly** [FrankerFaceZ/FrankerFaceZ#294]
**Web Browser**:
Google Chrome Version 61.0.3163.100

**Do you use BetterTTV or other Twitch extensions**:
Not currently with FFZ 4.0

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
N/A

**Bug / Idea**:
The usernames of people in chat "pulse" upon what seems like each new message.

GIF to demonstrate:
![pulse](https://i.imgur.com/VbKcJkT.gif)

**Steps to Reproduce (if Applicable)**:
This occurs when using the dark theme by twitch. It also occurs if you use the Grey (no purple) theme. It does NOT occur with the default white twitch theme.

Occurs irrespective of what colour adjustment preset is applied such as HSV Luma or Luv Luma (except for when "No color" is used then this issue doesn't occur).

Furthermore this actually happened with the previous FFZ before twitch rewrite HOWEVER not with the custom FFZ theme, it still occured with the twitch dark theme on the older FFZ.

**Comment by SirStendec** [comment]
This is a rendering bug with Chrome rather than anything FrankerFaceZ is responsible for. Unfortunately, I'm at a bit of a loss as to how I would mitigate the issue. It happens on Twitch's Dark Mode even without FFZ enabled.

I plan on asking one of my contacts who works on Chrome about the issue. Leaving it open for now for visibility.

**Comment by SirStendec** [comment]
Actually, I found a fix for this. Fixed in 0173212a365c4f7bcea1856b8f2ba830396ad5ba
