### ISSUE TITLE
Emotes in sub messages are not shown

### ISSUE THREAD

**Issue by XeroOl** [FrankerFaceZ/FrankerFaceZ#314]
**Web Browser**: Google Chrome Version 62.0.3202.94

**Do you use BetterTTV or other Twitch extensions**: I have FFZ: AP

**Bug / Idea**:
When announcing a subscription anniversary, FFZ emotes are not displayed.

Left is the legacy popout, and right is the new beta chat.
![bug](https://user-images.githubusercontent.com/6820998/32971833-c132d644-cbb4-11e7-978e-fe55da7d8e79.png)

**Steps to Reproduce (if Applicable)**: 
resub and put some ffz emotes into the announcement

**Comment by SirStendec** [comment]
This is a known issue because sub messages aren't considered normal chat lines and they are, for some reason, not rendered by the normal class that renders chat lines. I'm likely going to be changing their internal type to trick React into using the normal chat line renderer, and then detect my own properties on the message to know I need to show it like a sub line.

**Comment by SirStendec** [comment]
Fixed in 2e5fe7f17773061ddf16ddfb8773f955ef4d17d5
