### ISSUE TITLE
FFZ doesn't work on older versions of Google Chrome.

### ISSUE THREAD

**Issue by Dragonskull1057** [FrankerFaceZ/FrankerFaceZ#318]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ and the FFZ addon pack

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: I am currently forced to use an out of date version of Google Chrome since they are no longer rolling out updates for Windows Vista users. I tried using the current release of FFZ and it doesn't work at all on Chrome. It does work on Firefox (at least everything you guys have completed so far) but I was wondering if there is a chance a version will might be released for users with older versions of Windows?

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
This is because FrankerFaceZ is being written with modern JavaScript features, like async/await. Those were added in a version of Chrome released about 14 months ago.

I can't recommend that you continue using such an outdated version of Chrome, for security reasons. I understand why you wouldn't want to switch browsers, though.

Once I have time to work on it, I'm going to add a transpiler pass to our build system to generate more compatible JavaScript for older browsers. It just hasn't been a priority with all the other work to do.

I'd suggest switching to Firefox though. You're definitely playing with fire using a web browser more than a year out of date.
