### ISSUE TITLE
BTTV Gif Emotes are Static

### ISSUE THREAD

**Issue by gempir** [FrankerFaceZ/FrankerFaceZ#321]
**Web Browser**:
Chrome 62.0.3202.94
**Do you use BetterTTV or other Twitch extensions**:
FFZ + FFZ Add-on Pack
**Bug**:
BTTV Gif emotes are static. 

[video](https://giant.gfycat.com/ValidSpectacularHippopotamus.webm)

**Steps to Reproduce (if Applicable)**:

1. Add FFZ + FFZ Add-on Pack
2. Use SourPls or other gif emotes

**Comment by Dgc2002** [comment]
So I'm not super familiar with how FFZ and the addon pack used to interact. But this looks to be an issue on FFZ:AP's end.  
  
The FFZ:AP uses this url for the SourPls emote 
 
https://cache.ffzap.com/https://cdn.betterttv.net/emote/566ca38765dbbdab32ec0560/1x  
  
Removing `https://cache.ffzap.com/` results in an animated gif.  
  
That's because of [this section](https://github.com/Lordmau5/The-FFZ-Addon-Pack/blob/b4097db7bbd4856c7c1246b558a4841c633e2403/src/addons/bttv.js#L349-L359) in FFZ:AP.  
  
I **THINK** FFZ:AP needs to be updated to use the new settings menu to allow users to change the BTTV gif emotes from `Static Images` to `Animated Images`.

**Comment by SirStendec** [comment]
Dgc has it. FFZ:AP needs to be update it. Right now I've implemented a legacy API to allow it to continue working even in this reduced fashion. It's not great, it's not configurable, but the emotes are at least appearing.

Better, I think you'd agree, than the alternative? In any case, this is an issue for FFZ:AP. It should be fixed in a day or two as Lordmau5 has time to work on it.

**Comment by egeakat** [comment]
> So I'm not super familiar with how FFZ and the addon pack used to interact. But this looks to be an issue on FFZ:AP's end.
> 
> The FFZ:AP uses this url for the SourPls emote
> 
> https://cache.ffzap.com/https://cdn.betterttv.net/emote/566ca38765dbbdab32ec0560/1x
> 
> Removing `https://cache.ffzap.com/` results in an animated gif.
> 
> That's because of [this section](https://github.com/Lordmau5/The-FFZ-Addon-Pack/blob/b4097db7bbd4856c7c1246b558a4841c633e2403/src/addons/bttv.js#L349-L359) in FFZ:AP.
> 
> I **THINK** FFZ:AP needs to be updated to use the new settings menu to allow users to change the BTTV gif emotes from `Static Images` to `Animated Images`.

I'm having this exact issue. How do I fix this other than hoping an update rolls out?

**Comment by gempir** [comment]
Install FFZ and BTTV in your Browser and disable all BTTV emotes via FFZ and enable animated emotes in the actual BTTV settings

![image](https://user-images.githubusercontent.com/9765622/111909138-5acde780-8a5c-11eb-98d3-f9997fb2ba78.png)

**Comment by egeakat** [comment]
Thanks gempir Okayge

**Comment by calexil** [comment]
Having this same issue with ffz+bttvaddon, suddenly all my animated gif emotes are static

**Comment by egeakat** [comment]
> Install FFZ and BTTV in your Browser and disable all BTTV emotes via FFZ and enable animated emotes in the actual BTTV settings
> 
> ![image](https://user-images.githubusercontent.com/9765622/111909138-5acde780-8a5c-11eb-98d3-f9997fb2ba78.png)

this worked for me did you try this?

**Comment by gempir** [comment]
Like SirStendec already said this is an issue with FFZ:AP please don't spam old issues before reading the responses. 

If it is still and Issue please open an Issue here https://github.com/Lordmau5/The-FFZ-Addon-Pack

**Comment by Lordmau5** [comment]
Due to a rather recent change in FFZ you have to enable Animated Emotes within the Chat --> Appearance section in the FFZ Control Center
![image](https://user-images.githubusercontent.com/1345036/117570563-ef52de80-b0ca-11eb-93f6-912f71b6e41d.png)

**Comment by calexil** [comment]
@Lordmau5 Figured it out, thanks bub
