### ISSUE TITLE
FFZ doesn't work at all

### ISSUE THREAD

**Issue by Zoooook** [FrankerFaceZ/FrankerFaceZ#322]
**Web Browser**:
Chrome 51.0.2704.84 (64-bit)

**Do you use BetterTTV or other Twitch extensions**:
No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Is there any technical reason why this can't work on Chrome 51 or is it just version locked?

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
You are using an incredibly outdated browser more than a year old with numerous high risk security vulnerabilities. Stop that. If it's your computer, update Chrome. If it's a business, university, or otherwise not your machine to manage: contact the IT department. There is no excuse to be using a browser that is one and a half years old when web browsers are the most available surface for attacks in modern computing.

If you cannot upgrade Chrome for some reason, switch to Firefox. Just stop using such old software. It's not safe.


Onto your actual bug report, yes there's a technical reason. We are using async/await syntax, which was added to Chrome in version 55 (which itself was released 11 months ago). We are going to be adding a transpiling path to make the script accessible to older platforms, but that is a fairly low priority task because most users actually update their browsers.

**Comment by Zoooook** [comment]
That last paragraph was all I needed, thanks.
