### ISSUE TITLE
FFZ not working in VODs (new twitch)

### ISSUE THREAD

**Issue by forsenkappa** [FrankerFaceZ/FrankerFaceZ#330]
**Web Browser**: opera, chrome

**Do you use BetterTTV or other Twitch extensions**: bttv, ffz

**Bug / Idea**:
FFZ chat is not loading at all when watching a VOD, but emotes BTTV work.

**Comment by SirStendec** [comment]
This is a known "issue". We haven't re-implemented support for VODs in v4 at this time. It's lower priority than getting live chat working properly again, so it'll probably be a few weeks until it's in at least.

Leaving this open for visibility.

**Comment by Jfamig** [comment]
http://prntscr.com/hfwicf In VOD, player remembers custom chat width, VOD chat doesn't remember.

**Comment by forsenkappa** [comment]
Is there progress on this issue?

**Comment by sparcut** [comment]
@SirStendec I'd be eager to contribute if you had any direction, ideas or pointers for how you want to tackle this issue. Is VOD chat something that needs to be implemented separately or is there a problem with how its currently setup?

**Comment by SirStendec** [comment]
@sparcut VOD chat uses entirely separate code than normal chat. If you want to try supporting it, be my guest. You'll need to find the React classes for VOD chat lines and override their rendering, like I'm already doing for chat lines.

You'll also need to find whatever kind of container handles the business logic of loading and displaying lines so that you can register/unregister the appropriate room when it's needed to make FFZ load the associated emotes and other data.

It's not something that should be too difficult, just I haven't had time. I consider VOD chat a very low priority still.

**Comment by DiglidiDudeNG** [comment]
Would also love to hear more about what's being done for this issue. I watch a lot of VODs lately from a certain streamer I won't name, and the chat uses ffz emotes extensively.

**Comment by SirStendec** [comment]
For those curious about progress, what I've been working on recently is coming up with a unified data model for describing chat messages and trying to abstract rendering a bit further so that it's easier to render chat content in other contexts.

This is important since stream chat, rooms, whispers, enhanced viewer cards, vod chat, and clip chat all have different raw data but they all do basically the same thing.

**Comment by ANaPhOrAX** [comment]
is this still being worked on btw? I'd love to be able to filter messages from certain users on vod playback.. there's too many idiots on that site
