### ISSUE TITLE
Option to turn text into emoji like in BTTV

### ISSUE THREAD

**Issue by SamTheGr8est** [FrankerFaceZ/FrankerFaceZ#335]
**Web Browser**:
Firefox Quantim Stable
**Do you use BetterTTV or other Twitch extensions**:
FFZ:AP
**Idea**:
When you type the code for a certain emoji, it turns into that emoji. Like this: :thinking: becomes 🤔

**Comment by SirStendec** [comment]
We had emoji first. It's just not back in the rewrite yet.

To clarify, because I'm not sure what you mean with how vaguely this is worded: We support transforming emoji short codes into emoji characters in outgoing messages. This is done dynamically as you type or paste into the text area.

We do not transform short codes into emoji in incoming messages. If someone sends a message with `:fire:` we will not transform it into :fire:. That is objectively wrong, regardless of BetterTTV deciding to do things that way. Emoji are unicode codepoints and specifically not short codes. Short codes only exist to make them easier to input.
