### ISSUE TITLE
Theatre mode not filling whole screen. Possible solution found and detailed.

### ISSUE THREAD

**Issue by TarAlacrin** [FrankerFaceZ/FrankerFaceZ#347]
**Web Browser**:
Chrome, win10
**Do you use BetterTTV or other Twitch extensions**:
I use the extra emotes addon for ffz. Thats just about it
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
When you go into Theatre mode you'll notice that the picture doesn't expand to the edges all the way (specifically the bottom edge) this is really annoying. 

Its a simple fix though. 

Go into theatre mode, Hit dat f12, hit that select element. click on the video. scroll (usually up in the hierarchy in my experience) till you find the div:

`<div class="video-player__container player theme--dark" ...> 
`
Its usually the highest object in the html that Doesn't include that little black bar on the bottom.
This object has some inherited (im assuming inherited) css that is causing this issue:

```
.video-player--theatre.video-player--logged-in .video-player__container {
    bottom: 4rem; 
}

```
if you disable that by doing this:
```
.video-player--theatre.video-player--logged-in .video-player__container {
    /* bottom: 4rem; */
}

```
problem fixed. or if yall can inject some css and overwrite it that would probs also work. Would love for this to be fixed.

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
The padding at the bottom of the video player in theatre mode is there due to the whisper UI. FFZ already has an option to hide whispers, as well as an option to hide whispers specifically in theatre mode. Either one will remove the padding.

**Comment by ALongStringOfNumbers** [comment]
I also see this in the non-theater player, except the picture does not expand to the left and right side instead of the top and bottom mentioned in the above issue. 

It should also be noted that the black bar left on the sides of the player also causes the overlay button to be at the edge of the actual picture instead of the actual player where the padding is.  However, the overlay position is correct in theater mode, most presumably because there are no black bars on the side of the player in theater mode, instead they are on the top and bottom.

This might be because of some UI feature I have hidden, such as whispers, which in that case it is fine. However, if it is because a UI feature is hidden, it would be nice to have to overlay button move to the right side of the player instead of the picture.
