### ISSUE TITLE
Twitch chat pause setting

### ISSUE THREAD

**Issue by Harok9** [FrankerFaceZ/FrankerFaceZ#351]
On twitch if i hold CTRL for pause the chat on Twitch.tv it doesn't seem to work. Do i something wrong?

**Comment by SirStendec** [comment]
You need to have your mouse positioned over chat for things like holding Ctrl to work to freeze chat. Alternatively:

Sometimes, Twitch's scrolling code can break and stop freezing correctly. This happens with or without FrankerFaceZ enabled and unfortunately I don't have a clue how to fix it, at this point. You can tell when this happens because chat will keep scrolling even with Twitch's own "More messages below." displayed at the bottom of chat.

Either way, I doubt this is actually a FFZ bug.

**Comment by Harok9** [comment]
It doesn't matter if i hover the mouse or not. Also i set the setting to CTRL to pause the chat. Whatever setting i use it doesn't work. i have Firefox quantum

**Comment by SW1FT** [comment]
This is also a problem for me on Firefox 59.0a1.
