### ISSUE TITLE
emotes show with additional text attached 

### ISSUE THREAD

**Issue by rivnam** [FrankerFaceZ/FrankerFaceZ#375]
**Web Browser**:
chrome with https://multistre.am/

**Do you use BetterTTV or other Twitch extensions**:
ffz add on pack; ffz enhancing addon

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
http://putco.de/NzY2Ng.log

**Bug / Idea**:
emotes normally on my chat window but on the other end certain letters appear after the emote. i.e "pokketSMART" showed the emote and "ART"; "BegWan" shows the emote and "n"

**Steps to Reproduce (if Applicable)**:

tbh i have no idea. I've only realised this from the clip below (near the end), and when streamers have chat on their video, i can see my msg which looks different on my chat screen. Anxiety typos 2.0 ugh

https://clips.twitch.tv/RacyBeautifulAlfalfaDancingBanana

**Comment by SirStendec** [comment]
I assume you're talking about this:
![image](https://user-images.githubusercontent.com/14036657/35477585-f3263440-0393-11e8-8734-291db086634e.png)

That is not a problem with FrankerFaceZ. That is a problem with Twitch's chat renderer for clips. If you see the bug in a streamer's on-screen chat, that's a problem with their on-screen chat.

Emotes are handled on the chat server. The server scans your message for emotes, and then it sends a list to the client with each message saying where the emote is. For example, `Example Kappa` has an emote (emote no. 25 specifically) from character 9 to 13. It'll send something like `25:9-13` to the client.

The client then has to replace those specific characters with an image of the emote. The problem is that most clients use JavaScript to do this, and JavaScript is bad at strings. Most programming environments dealing with unicode strings deal with individual code points. JavaScript doesn't. So you run into the fun situation where a character that every reasonable bit of software knows is a single character is, by JavaScript, treated like it's two character.

Take this thinking emoji: 🤔

It's obviously one character. Python knows it's one character. But ask JavaScript for the length? Two.

![image](https://user-images.githubusercontent.com/14036657/35477624-2e7d674c-0395-11e8-8456-494e852f3c2a.png)

Because emotes are identified by where they are in the string, having JavaScript disagree with how long characters are breaks pretty much everything and you end up seeing emotes not actually aligned with their codes, as you've described.

FFZ has special code to handle these characters to make sure emotes are aligned correctly, hence why your emotes appear in the right spots. If you're seeing them placed incorrectly elsewhere, it's problems with that other software and it should be reported to those developers.

I hope I've cleared that up a bit for you.
