### ISSUE TITLE
Twitch Panels on page get cutoff by chat

### ISSUE THREAD

**Issue by Fluzzarn** [FrankerFaceZ/FrankerFaceZ#383]
**Web Browser**:
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
**Do you use BetterTTV or other Twitch extensions**:
Nope
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:
Twitch Panels go under chat box instead of wrapping around to a new row

**Steps to Reproduce (if Applicable)**:

FFZ:
![image](https://user-images.githubusercontent.com/2403362/36520553-9d7ae5e2-175f-11e8-909c-3242eaaa20d5.png)

Incognito Mode without FFZ:
![image](https://user-images.githubusercontent.com/2403362/36520565-b145ff80-175f-11e8-9fce-091245e58c1a.png)

**Comment by SirStendec** [comment]
This bug has existed for years, and it's an issue with Twitch and not at all related to FFZ.

Twitch uses a JavaScript library called Masonry to manually position the panels with minimal wasted space. I'm not sure if the bug is with Masonry or a fault with Twitch's own code not telling Masonry to update, but occasionally you'll run into the problem of panels being too wide.

When this happens, try minimizing the left or right sidebars and then re-opening them. This should force the panels to re-flow. You can also resize the window.
