### ISSUE TITLE
New messages in chat are cut off

### ISSUE THREAD

**Issue by jerhms** [FrankerFaceZ/FrankerFaceZ#391]
**Web Browser**:
Chrome **65.0.3325.162 **
**Do you use BetterTTV or other Twitch extensions**:
Only have FFZ and the FFZ Add-on Pack.
**Bug / Idea**:
New messages are slightly cut off. Don't know why this happens, either. It's entirely random.
https://i.imgur.com/gqf2XDz.png
After typing another message to move the cut off message up, it fixes it. https://i.imgur.com/sFMUXNr.png

**Comment by SirStendec** [comment]
That generally happens when an emote image hasn't loaded yet. Your browser doesn't know how tall the chat line is going to be. It isn't tall enough, so it's resized when the image finishes loading, but by then the chat already finished scrolling and won't update till you do it or the next message comes through.

Your usage of the baseline emoticon alignment is making the problem worse because images are raised up compared to the rest of the message.

There's not much to do about the issue without installing lots of costly event handlers, and aside from that legacy chat is going to be discontinued by Twitch at the end of the month. As such, I won't be addressing this.
