### ISSUE TITLE
manifest.json incomplete

### ISSUE THREAD

**Issue by gempir** [FrankerFaceZ/FrankerFaceZ#400]
**Web Browser**:
Chrome 65.0
**Do you use BetterTTV or other Twitch extensions**:
No
**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:
/

**Bug / Idea**:
Manifest json is incomplete:

The 'manifest_version' key must be present and set to 2 (without quotes). See developer.chrome.com/extensions/manifestVersion.html for details.

Note: manifest_version is not the only thing missing, if I add it it complains about "name" missing. So there is more.

My manifest.json:
`{
  "avalon.js": "avalon.cc02e3c0777dddabcb6b.js",
  "avalon.js.map": "avalon.cc02e3c0777dddabcb6b.js.map",
  "ffz-fontello.ttf": "ffz-fontello.25bbf19a5956fadc65a9476512edd5fe.ttf",
  "ffz-fontello.woff": "ffz-fontello.f2298c8397fec1c26d918f165926862b.woff",
  "ffz-fontello.woff2": "ffz-fontello.881f3f64debb12ab26b3106b63b7de32.woff2",
  "host-options.js": "host-options.a30933bcadb42e3464a8.js",
  "host-options.js.map": "host-options.a30933bcadb42e3464a8.js.map",
  "main-menu.js": "main-menu.bd07bc6844139bc1eaf4.js",
  "main-menu.js.map": "main-menu.bd07bc6844139bc1eaf4.js.map",
  "main.css": "main.a0f7a1f0ef8ae2f82bcf78ed8268100b.css",
  "site-css-tweaks.js": "site-css-tweaks.f2b367e3edf922a7c0aa.js",
  "site-css-tweaks.js.map": "site-css-tweaks.f2b367e3edf922a7c0aa.js.map",
  "theme.css": "theme.37e5cd6d035a85a5b55070febf04ef95.css",
  "vue.js": "vue.41e80f0eec1f4c5452f1.js",
  "vue.js.map": "vue.41e80f0eec1f4c5452f1.js.map"
}`

**Steps to Reproduce (if Applicable)**:
* clone repo
* npm install
* npm build
* Under chrome://extensions/ load unpacked Extensions (load dist folder)

**Comment by SirStendec** [comment]
The manifest.json that is created when you build FrankerFaceZ is not intended to function as part of a browser extension. The file is, in the future, going to be used to set up redirects in our CDN for caching purposes. `//cdn.frankerfacez.com/script/avalon.js`, for example, will use a 302 redirect to direct the browser to `//cdn.frankerfacez.com/script/avalon.cc02e3c0777dddabcb6b.js` given the data you posted.

The build output in general is not meant to be used as a browser extension of the kind you would load via `chrome://extensions/`. The output is a script that we host in our CDN that must be injected into the context of a Twitch page. We do it this way rather than building a browser extension because it allows us to update quickly whenever Twitch makes a change that breaks functionality with FFZ.

The injection is done with our simple browser extensions or with the user script available at https://cdn.frankerfacez.com/script/ffz_injector.user.js

They all work the same way. If you want to run a local copy of the script, please run the development server as indicated in the project's read-me.
