### ISSUE TITLE
[Feature Request] Timestamps In Seconds, Old Profile Pop-Up

### ISSUE THREAD

**Issue by Cxyzis** [FrankerFaceZ/FrankerFaceZ#428]
**Web Browser**:
Chrome

**Do you use BetterTTV or other Twitch extensions**:
FFZ:AP

**Idea**:
- Can we have timestamps also in seconds like we had before Twitch changed the layout?
- Can we have something similar to the old profile pop-up? (How old is your account is, for how long you've been following a channel, old aliases, etc.)
- This is a more niche request I believe: An option to use the old way for auto completing Twitch/FFZ/BTTV emotes. (ex: Write "Pog" and then press _**Tab**_ to open the list, then select the emote you want and press _**Enter**_ to write it in the chatbox.)

**Comment by Lordmau5** [comment]
- That's on the to-do list from what I know; No ETA though
- This is part of the upcoming mod-cards and yes, that's gonna be implemented. Aliases is not yet implemented from what I know, but shouldn't be *too* difficult.
- That is also on the to-do list; The only reason it's currently using Twitch's way with the colon (**:**) is because FFZ doesn't modify that part of the chat handler yet. It's planned though, as custom commands are going to be making a return, too.
