### ISSUE TITLE
Clear chat when show deleted messages is on

### ISSUE THREAD

**Issue by ghost** [FrankerFaceZ/FrankerFaceZ#43]
**Idea**: When the option to show deleted messages is enabled and someone clears the chat with the /clear command, only the message `A moderator's attempt to clear chat was ignored.` shows up.

My idea is to add another "mode" to the show deleted messages option to show deleted messages like it does but to execute /clear commands properly.

**Comment by Anonic** [comment]
I'd like the exact opposite of this. I was going to Feature Request the options being unpaired as the simplest implementation. I believe this is similar to the options in BTTV.
Example:

Show Deleted Messages
Fade deleted messages instead of replacing them.

Disable Clearing Chat
Prevent chat from being cleared.

**Comment by Kajanor** [comment]
Prevent chat from being cleared as it's own option and Prevent chat from being not cleared as a mode of the Show deleted messages option doesn't make a difference to me.

But one of these two would be cool to have.
