### ISSUE TITLE
Freeze Chat Scrolling - not working

### ISSUE THREAD

**Issue by Demonikki** [FrankerFaceZ/FrankerFaceZ#433]
With high volume of messages, Freeze Chat Scrolling (On Hover) slows down chat, but it keeps moving (slowly). Mouse is kept constantly moving. The "Chat paused due to mouse movement" message still displays.

Latest version of FFZ

**Web browser**: Firefox 59.0.2 (64-bit).
**Do you use BetterTTV or other Twitch extensions**: Yes, BBTV

To reproduce - pause chat by hovering over it (this works). Then stop moving the mouse (chat scrolls again). Click somewhere else (I clicked on video). Now, moving the mouse fails to pause chat.

**Comment by Demonikki** [comment]
[https://youtu.be/l-pSJRlpje8](Video of issue)

**Comment by SirStendec** [comment]
This is not a FrankerFaceZ bug. This is a Twitch bug. Their chat scrolling code is broken on Firefox. Here's a GIF of Twitch with no extensions, with chat in the state where it should be frozen. You can tell native Twitch scroll lock is in place because of the `More messages below.` message. It's clearly not working.

![2018-04-30_18-49-34](https://user-images.githubusercontent.com/14036657/39454109-5fc928b2-4ca7-11e8-81ac-73e16dd67dc1.gif)

Please direct this issue to Twitch. I don't currently have sufficient understanding of the internals of their scroll locking system to try fixing it with FFZ and there are more important features I need to finish.

**Comment by kasper93** [comment]
@SirStendec You could incorporate workaround used in this addon https://addons.mozilla.org/en-US/firefox/addon/twitch-chat-scroll-fix/ Anyway I send email to Twitch, maybe they will fix and a lest tell why it doesn't work on FF. I don't want to invest time in debugging this :)

**Comment by ncla** [comment]
Seeing as this is still a problem, maybe it is worth incorporating the fix that the previously mentioned extension has? You can view the source code of the extension with CRX viewer extension.

Here's the code: https://gist.github.com/ncla/300cde991b9ab660ca63b6611e8563af
