### ISSUE TITLE
Tab-completion for emoji do not work 

### ISSUE THREAD

**Issue by TenebrisLuxNoctis** [FrankerFaceZ/FrankerFaceZ#445]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**Bug / Idea**: Bug : impossible to autocomplete emojis'name

**Details**:
I'm trying to use the Tab-completion for emoji, but when I'm trying to hit tab, it's only giving me usernames propositions.

I've some errors in browser console, I don't know if it is linked to my problem : 

VM75506:164 WebSocket connection to 'wss://127.0.0.1:8003/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

viewer.html:1 Failed to load https://twitch-extensions.pixlfox.com/now-playing/42141251/playing.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://h7683cdyci11yov0tlac9f6lkvgtzi.ext-twitch.tv' is therefore not allowed access. The response had HTTP status code 520. (**It can also be a 522 status code for the same file**)

![errors ffz in browser console](https://user-images.githubusercontent.com/30625135/40824687-601a8478-6575-11e8-8c97-26aa644d4400.PNG)
(*The console is full of these errors*)

Thank you for attention.

**Comment by SirStendec** [comment]
Tab-completing emoji currently requires you to start your input with `:`, just like vanilla Twitch does. We're just hooking into the built-in Twitch feature at this point. Proper support for tab-completion and other input actions will come later.

The WebSocket connection issues are because you have changed your socket server cluster setting. Go to Debugging > Socket and set it back to Production.
![image](https://user-images.githubusercontent.com/14036657/40841325-17a1f796-6578-11e8-82a9-16f1f417c73a.png)
