### ISSUE TITLE
FFZ Suddenly not working overnight

### ISSUE THREAD

**Issue by DrOutside** [FrankerFaceZ/FrankerFaceZ#487]
**Web Browser**: Chrome

**Do you use BetterTTV or other Twitch extensions**: No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**: N/A

**Bug / Idea**: FFZ wont work at all

**Steps to Reproduce (if Applicable)**: Not sure.

Hi! So my FFZ was working flawlessly only the night before and I didn't restart my PC, install anything new or update anything since I woke up and now FFZ wont work at all.

I've tried reinstalling FFZ, restarting my PC and restarting Chrome.

BTTV works fine if I try to install that.

I'm not sure what's going on here, I can't even access the FFZ Menu to get the logs.

Is this a current known issue or is this on my end?

**Comment by thatfunkymunki** [comment]
Same issue, I get grayed out FFZ icons in the top right but no functionality 
![image](https://user-images.githubusercontent.com/1043913/42931498-8e89e354-8adb-11e8-9021-4c870d96c024.png)

**Comment by SirStendec** [comment]
This issue was caused by communication problems between FrankerFaceZ's web host and Cloudflare, the CDN we use. Unfortunately it took support quite a while to get it fixed and we weren't able to do anything to speed things up.

There are still some users reporting issues on Twitter, but their issues are with connecting to Cloudflare at all which indicates a networking issue between the user, their ISP, and Cloudflare. Not a problem that we can fix or that we're even really involved with.

If you are still having loading issues, try connecting to https://www.frankerfacez.com and https://www.frankerfacez.com/cdn-cgi/trace

If you can't load the first link but you can load the second one, please reply with the `colo=` value from the second link and I'll re-open this issue. If you can't load either link, contact your ISP for networking support.
