### ISSUE TITLE
Chat keeps disconnecting after a few minutes

### ISSUE THREAD

**Issue by timeshifter** [FrankerFaceZ/FrankerFaceZ#543]
**Web Browser**:
Chrome and Firefox, both updated

**Do you use BetterTTV or other Twitch extensions**:
No

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**:

**Steps to Reproduce (if Applicable)**:
I just go to any Twitch channel and wait a few minutes. Chat always dies. This has been happening for *months*.

**Comment by ikuni-potata** [comment]
i do have the same issue. if chat goes too quiet, it disconnects and only reconnects after i've sent a new message. 
i also use bttv but i tested it and the chat disconnects with bttv or without it but it reconnects itself automatically so that the only annoyance is the constant "welcome to the chat" message. 
only if i use ffz it stops reconnecting.

**Comment by anchuin** [comment]
Having this issue for a while now but finally come around to report it. Same conditions as @timeshifter above.
Chat doesn't display any messages after "welcome to chat" appears, and will only reconnect when writing a message myself. Sometimes messages will show up again, but most of the time only after reloading the page. 

Log can be found here: https://putco.de/MTA4NTY

**Comment by timeshifter** [comment]
So it turns out this is actually a *Twitch* issue, and nothing to do with the extensions. Every websocket connection to Twitch chat will randomly disconnect. The raw IRC connection does not. Twitch done a Twitch with their own chat...
