### ISSUE TITLE
What does the dropped frames mean

### ISSUE THREAD

**Issue by Bren002** [FrankerFaceZ/FrankerFaceZ#549]
**Web Browser**: chrome

**Do you use BetterTTV or other Twitch extensions**: both

**FFZ Logs (via FFZ Menu > About > Logs; if Applicable)**:

**Bug / Idea**: What does the dropped frames mean https://imgur.com/a/jpKZrld

**Steps to Reproduce (if Applicable)**:

**Comment by SirStendec** [comment]
Dropped Frames is pulled from the video element used by the player to show video. It's a count of how many frames of video your browser has skipped (or "dropped") rather than displaying. You might notice a stutter in the video you're watching when frames are dropped.

Frames are commonly dropped because the browser doesn't have enough time to draw the frame before it should draw the next one. Your browser would do this because it was too busy drawing other parts of the page, such as chat.
