### ISSUE TITLE
FFZ puts "hat emotes" in the wrong position

### ISSUE THREAD

**Issue by AldarisStarcraft** [FrankerFaceZ/FrankerFaceZ#553]
**Web Browser**: Google Chrome

**Do you use BetterTTV or other Twitch extensions**: FFZ, BTTV

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log; if Applicable)**:

**Bug / Idea**: When FFZ is enabled, the hat BTTV hat emotes like SoSnowy/IceCold etc ... have the wrong position. They should in the same position as the emote but with FFZ, they are placed at the right of the emote. I'm forced to disabled FFZ cause of this, because I love those hat emotes so much ... Please fix this !

Wrong position (with FFZ) :
![wrong_position](https://user-images.githubusercontent.com/28606292/49724934-d8460300-fc6a-11e8-9050-f5000aa28bdd.png)

Normal position (without FFZ) :
![normal_position](https://user-images.githubusercontent.com/28606292/49724933-d8460300-fc6a-11e8-8690-21a3bb384707.png)

**Comment by SirStendec** [comment]
This is an issue with the FFZ Addon Pack and not FFZ. The author of that extension is aware and will be releasing an update as soon as he has time at his PC. This happens every year because BetterTTV's overlay emotes are not marked in any way in their API, and FFZ:AP has to hardcode them the same way BTTV itself does.

Leaving this open until it's fixed to make sure no one comes to post it without seeing this.

**Comment by Eldresh** [comment]
I don't use the FFZ Addon Pack and I'm having this same issue. I only use BTTV and FFZ. Would an issue with the FFZ Addon Pack still affect me even without it being installed? Disabling FFZ itself fixes this issue for me.

**Comment by SirStendec** [comment]
Hmm. It looks like BetterTTV is using overly specific CSS to re-position their emotes, and it's not triggering with FFZ because we don't wrap emotes in completely unnecessary span elements like unmodified chat does.

Frankly, I don't have the time to mess with this right now. I'd suggest just using FFZ:AP for BTTV emotes and not BTTV if it's super important to you.
