### ISSUE TITLE
[Feature request] Embed image tooltip into chat

### ISSUE THREAD

**Issue by mikaelssen** [FrankerFaceZ/FrankerFaceZ#554]
Can we get an option to 'embed' the tool-tips into chat directly under the message or above? 

This makes it a lot simpler to read chat when links get posted and you're in an un tabbable game and can't hover/click the link.

Basically like how discord does it i guess

**Comment by SirStendec** [comment]
Adding full sized embeds into chat isn't something I'm really willing to do. It looks a bit ridiculous. (See: https://twitter.com/SirStendec/status/1072627871523504129)

I do like the idea somewhat though. My current implementation plan is displaying limited information in a tiny embed similar to how Twitch Clips and Twitch Videos do currently when linked in chat. It should still provide enough information about what was linked without taking up several hundred pixels of height.

Other Thoughts:
* Definitely off by default
* There should be settings for Rich Embeds so that they only display for links posted by users of certain permission levels. For example, only show Rich Embeds for links from Mods and VIPs. Or from Subs, Mods, and VIPS.
