### ISSUE TITLE
AI Superscaling for low-res emotes using Waifu2x (with example photos)

### ISSUE THREAD

**Issue by SheinH** [FrankerFaceZ/FrankerFaceZ#569]
**Is your feature request related to a problem? Please describe.**
Some emotes such as BabyRage look ugly because they are lowres:

![image](https://user-images.githubusercontent.com/5853497/52171297-88466280-2728-11e9-9376-874371bc40dc.png)

**Describe the solution you'd like**
[Waifu2x](https://github.com/nagadomi/waifu2x) offers AI super scaling for images and the results look very good. Perhaps you could offer superscaled versions of low res emotes as a toggle.

As an example, here is BabyRage scaled 4x with some minor touchups in photoshop:

![84bdf854-7ca0-433c-b40b-ae236cababb0](https://user-images.githubusercontent.com/5853497/52171314-d3f90c00-2728-11e9-9ae4-738ef69de954.png)

This is much nicer to look at compared to the pixellated mess above and it only took me a couple minutes to make.

**Comment by SirStendec** [comment]
I am interested in offering upscaling methods for users once the new FFZ website is complete, so that users can attempt to improve the quality of legacy emotes that don't have high DPI images.

That said, I don't plan on adding high-DPI versions of non-high-DPI Twitch emotes. There are a ton of them, it's highly subjective, and Twitch should fix it themselves.
