### ISSUE TITLE
Prime Subscription and Loot Reminder Deactivate in the Player??

### ISSUE THREAD

**Issue by Dan-Y89** [FrankerFaceZ/FrankerFaceZ#590]
**Is your feature request related to a problem? Please describe.**

I am disturbed by the Prime Reminder in the player, constantly you have to set this to invisible. Is there no option to remove it completely? Other player overlays can continue to work, only for Twitch prime is very disturbing. 
Thank you

**Comment by SirStendec** [comment]
Blocking specific extensions is beyond the work I want to perform with FrankerFaceZ. Rather than FFZ, I'd suggest using an ad-blocker to handle that. Each extension has its own unique sub-domain, so it's just a matter of finding the correct subdomain and blocking that.

As an example, the Prime sub reminder is on `d4uvtfdr04uq6raoenvj7m86gdk16v.ext-twitch.tv` so if you block that domain, it will fail to load into the player. Hope that helps.
