### ISSUE TITLE
Unable to reply to chat messages when using Chat on Videos

### ISSUE THREAD

**Issue by palmtopturtle** [FrankerFaceZ/FrankerFaceZ#592]
**Describe the bug**
When enabling FFZ chat on videos, you lose the ability to reply to past chat messages.

**To Reproduce**
1. Enable chat on videos
2. Context menu when hovering over chat messages doesn't appear

**Expected behavior**
The context menu appears when hovering over chat messages from past VODs

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73
 - Other Extensions: uBlock Origin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://putco.de/MTEwOTA

**Additional context**
I swear I remember this was working in the past.

**Comment by SirStendec** [comment]
This is nothing new. The context menu is a pain to implement, so we just haven't for now. You should be able to click a Reply button on vod messages. 
![image](https://user-images.githubusercontent.com/14036657/56329648-733b7600-6152-11e9-93c3-3180953fbe4e.png)

When you do that, FFZ disables its own renderer for that message, so the context menu should also become available. Otherwise, you can just disable FFZ's handling in general in the control center.

I know that's not optimal, but I'm not interested in finishing the full implementation at this time. I don't have the time to do it, for that matter.

**Comment by palmtopturtle** [comment]
Gotcha. However, I'm not even seeing the reply button for some reason. Here's a screenshot (using latest version of FFZ): 
![Capture](https://user-images.githubusercontent.com/42655839/56332187-50fb2580-615d-11e9-841e-01fdaed9038d.PNG)

**Comment by SirStendec** [comment]
And you see the Reply button with FFZ disabled, on that exact video? They may have changed the code I use to detect if it's allowed to post comments or not.

**Comment by palmtopturtle** [comment]
Yeah. Rather, I see the context menu which has the reply button when "chat on videos" is disabled... perhaps that might be the cause of the issue? I'm not sure if it was different before, but you have to click the context menu when hovering over a chat message in order to get the reply button to show up.
