### ISSUE TITLE
[Feature Request] Remote/Private Addons

### ISSUE THREAD

**Issue by duurland** [FrankerFaceZ/FrankerFaceZ#609]
**Context**
I'd like to provide a script I've created to a handful of people, the script is only relevant to a few people (mods of a certain channel) so it doesn't make sense to list it publicly. I'd love if it was possible for FFZ to load addons from a remote server, as we're all using FFZ already .

**Describe the solution you'd like**
An option for users to add additional urls loaded by [AddonManager.loadAddonData](https://github.com/FrankerFaceZ/FrankerFaceZ/blob/8582626269eded92e2e8412470f784278ae00509/src/addons.js#L120)

**Comment by Lordmau5** [comment]
If it's just mods of a certain channel you could consider writing a userscript that waits for FFZ to load and then injects a custom script from said remote server.

Rough template for a loader script (similar to what I've used in FFZ:AP before):
https://paste.gg/p/Lordmau5/afa4511a6ed346c0a883ea4e8c602e26

**Comment by duurland** [comment]
I thought about it, and may be what I'll end up doing.

However, I'd very much prefer not being dependent on another additional extension, so many people already got FFZ installed. If this feature was added I'd certainly create more niched addons in the future.

Thanks for the template, saving it, just in case :)

**Comment by SirStendec** [comment]
I'm going to have to reject this idea, unfortunately. While I do like flexibility, I am concerned about the security implications. I don't want to let users use FrankerFaceZ to load JavaScript that is outside of my control. 

Rather than loading external add-ons, I'd suggest that this solution might be handled by letting add-ons be declared as unlisted. Those add-ons would not appear in the Add-Ons UI until such time as users performed some activity to unlock them, such as entering a code.

That way, the add-ons will still go through code approval and be hosted on the FFZ servers.
