### ISSUE TITLE
Add ability to embed user avatar in /room/

### ISSUE THREAD

**Issue by mylogon341** [FrankerFaceZ/FrankerFaceZ#611]
When calling `/room/:userId` I would like to be able to embed (or have it embedded by default) into the user avatar in the `room` object. An ideal example response would be

```
{
    "room": {
        "_id": 1936,
        "css": null,
        "display_name": "name",
        **"avatar": "URL TO CDN HERE",**
        "id": "name",
        "is_group": false,
        "mod_urls": null,
        "moderator_badge": null,
        "set": 1937,
        "twitch_id": 25242370,
        "user_badges": {}
    },
    "sets": {
        [...]
    }
}
```

**Comment by SirStendec** [comment]
We won't be doing that. Our current website doesn't frequently update the avatar field. In fact, it only updates when that user logs into our site, so it's quite frequently out of date, and I don't want to be passing stale data to consumers of our API.

----

As for the future, I'm currently working on v2 of our API and we aren't even storing the avatar in the database for that version of the site. Instead, we'll have special endpoints on our CDN that use a 302 redirect to forward the browser to the user's avatar. We'll be doing loading from Twitch's API on demand to keep things fresh with a short duration redis cache.

Example (which is not live yet and won't be for a while):

```console
stendec@api-test:~$ curl -i https://cdn.frankerfacez.com/avatar/49399878
HTTP/1.1 302 Found
Vary: Origin
X-Clacks-Overhead: GNU Terry Pratchett
Cache-Control: public,max-age=300
Location: https://static-cdn.jtvnw.net/jtv_user_pictures/sirstendec-profile_image-1514bdb9d03a0954-300x300.png
Content-Type: text/plain; charset=utf-8
Content-Length: 100
Server-Timing: routing;dur=0.855, validation;dur=0.183, cache;dur=1.750, total;dur=5.146
Timing-Allow-Origin: *
Date: Mon, 24 Jun 2019 01:33:24 GMT

https://static-cdn.jtvnw.net/jtv_user_pictures/sirstendec-profile_image-1514bdb9d03a0954-300x300.png
```

That said, this endpoint might end up with an origin check because it's only intended for use via our website. Third parties should, frankly, be gathering the Twitch data they need *from* Twitch.

**Comment by mylogon341** [comment]
That is fair. Tbh, I didn't even consider going straight to twitch, for some reason - got it set up now. Thanks.
