### ISSUE TITLE
No longer working in Pale Moon

### ISSUE THREAD

**Issue by mintoyatsu** [FrankerFaceZ/FrankerFaceZ#629]
**Describe the bug**
Upon installing the FFZ extension or userscript, the FFZ menu and emotes do not appear. The script is injected into the head but does not function.

**To Reproduce**
1. Go to the FrankerFaceZ website.
2. Click on 'Download for Pale Moon'.
3. Install the extension.
4. Go to any Twitch channel.

**Expected behavior**
FFZ menu button should appear in the top right of the page header.

**Environment**
 - OS: Windows 7 Professional 64-bit
 - Browser: Pale Moon
 - Version: 28.6.1

**Additional context**
FFZ was working correctly in Pale Moon about a week ago (version 4.6.1). I'm guessing versions 4.6.2, 4.7.0, or 4.7.1 caused this regression. Notably, several dependencies were updated in version 4.6.2 which may be the culprit.

**Comment by Lordmau5** [comment]
We had 2 similar cases with users being on a 2 year old Chrome version **AND** a 3 year old Firefox version respectively.
FFZ didn't work for them either.

Version 4.6.2 brought in a bunch of package updates, so I'm not surprised it broke some legacy stuff.

I've installed Pale Moon and I wonder why people are still sticking to it - the UI feels like it's straight out of 2008 and coupled with these issues, it wouldn't surprise me if that specific fork didn't support anything newer than IE7 standards.

Seeing as 28.6.1 is the newest version, there are 3 ways to go about this:
- Switch to another browser (Seeing as Pale Moon is a Firefox fork, why not just ... go with Firefox itself?)
- Wait for the Pale Moon developers to advance out of the stone age and support new browser / JavaScript specifications and / or standards
- Wait for Stendec to see about a potential fix within FFZ (which I doubt, but hey, these are mainly my 2 cents to this issue)

**Comment by SirStendec** [comment]
I just loaded up Pale Moon and checked, and it seems to be giving a SyntaxError. Further, it's giving a totally useless SyntaxError as the code it has indicated contains a syntax error has not changed since Pale Moon was still working.

Basically, Lordmau5 is correct and Pale Moon is an outdated browser. If anyone wants to dig into this and find out what exactly is the problem, please be my guest. I won't be doing anything about the issue, however. The developer tools are useless and I have no intention of digging through that much code manually.

**Comment by SirStendec** [comment]
Fixed in 9ab57897efa5632f6bc4820b7fce5711b48edbe4
