### ISSUE TITLE
FFZ for Opera GX

### ISSUE THREAD

**Issue by yllwsnw** [FrankerFaceZ/FrankerFaceZ#655]
Hi wanted to ask whether there are already plans towards support on Opera's new browser called Opera GX.
I tried using the regular opera version of ffz to see if it would work, didn't work for me. Also using stuff like "Install Chrome Extensions" and then downloading the chrome version, didn't seem to work out neither.
Thanks in advance

**Comment by SirStendec** [comment]
We have no plans to go out of our way to support Opera. Opera uses WebKit for their browsers, so everything should just already work. If it doesn't, that indicates an issue with Opera rather than something with our own product.

Chrome, Chromium, Safari, standard Opera, and the new Edge are all WebKit-based and they all work fine.
