### ISSUE TITLE
Option to disable the new theme function

### ISSUE THREAD

**Issue by dansa** [FrankerFaceZ/FrankerFaceZ#666]
I'd like you to consider an option to disable the Theme > Colors system entirely because the use of !important(why?) on every css rule will likely be interfering with other 3rd party styling.

Or, have the system not use placeholder values with !important that force a default color when no options has been set.

**Comment by SirStendec** [comment]
Twitch's new CSS system relies on the use of color variables for changing the appearance of the website. This is great, because it makes things much easier to customize. You just need to override a variable and suddenly, everything is different. This especially cuts down on the volume of CSS needed to support a separate dark theme, since the dark theme generally only needs to override the color variables and it all just works.

The rules you are complaining about are patches over areas of Twitch's CSS that were overlooked or simply not touched upon yet when integrating variables. I am doing nothing more than assigning the proper color variable so that the element will react when a variable is assigned. I fully expect my own patches to become unnecessary in the future as Twitch fully switches to CSS variables for colors. I am not assigning colors anywhere that a color is not already set, and I'm not assigning variables that do not have values or that do not make sense.

I am using `!important;` so that I may continue writing concise selectors. Would I not include important, I would have to increase the complexity of the selectors I'm using in order to ensure they apply. I believe that doing so would make the CSS more difficult to maintain and for other third-parties to deal with than what I am currently doing. Especially given that third parties should already be used to working around `!important` given how liberally Twitch's own site makes use of it.

That said, third parties should also be updating their own solutions for Twitch's appearance to take advantage of the variables. If you want to customize the color of an element, consider overriding the color variables that element uses. If that is not sufficient for your purposes, my rules are still very basic and you can just write your own slightly more specific rule that also uses `!important`. Or you can inject your styles via a user agent rather than the page context, giving them further priority.

---

It is likely that, in a future release, FFZ will only load the CSS patches when a custom theme has been selected, but I can't and won't say for certain until I know how I'm going to develop the theme system for sure.
