### ISSUE TITLE
Next version of API?

### ISSUE THREAD

**Issue by Galiullinko** [FrankerFaceZ/FrankerFaceZ#668]
**Is your feature request related to a problem? Please describe.**
I want to make a bot for automatically changing emotes on twitch channels. But APIv1 doesn't have endpoints for adding or removing emotes from the channel.

**Describe the solution you'd like**
Are you planning to implement those endpoints in the near future?

**Describe alternatives you've considered**
I'll maybe try to parse HTML of FFZ control panel, but with the API it will be much easier. Not only for me, but also for many new projects.

**Comment by SirStendec** [comment]
Version 2 of our API is under active development, and it will make that easy to do. It supports OAuth and pretty much everything you can do on the site you'll be able to do with the API. Follow us on Twitter or join our Discord for announcements when the new API is released.

It will still be another month or two, most likely, since we need to build a website to go on top of the API also.

**Comment by Galiullinko** [comment]
Thank you for response 👍
