### ISSUE TITLE
Darkmode inverted after changing background color

### ISSUE THREAD

**Issue by Marenthyu** [FrankerFaceZ/FrankerFaceZ#707]
**Describe the bug**
When Twitch's native dark mode is enabled and one changes the background color using FFZ's background color picker, then resets it using the x next to the color input, the background will turn to twitch's default white and toggling the dark mode inverts the color exactly the wrong way.
Persists until refresh.

**To Reproduce**
1. Enable Twitch's native dark mode
2. Open FFZ Control Center
3. Change background color under "Theme"
4. Click x to reset the color
5. Observe actual background color while toggling dark theme selector

**Expected behavior**
Reset to native dark mode if it was enabled prior to changing the option instead of the light mode.

**Screenshots**
https://lowee.de/2019-12-06_17-12-27.mp4

**Environment (please complete the following information):**
 - OS: Windows 10 [1909]
 - Browser Chrome 79.0.3945.74 (Beta)
 - Version 4.17.0 [1fe7c41]
 - Other Extensions: The FFZ Add-On Pack 3.1.1, BetterTTV 7.2.72 (plus plenty others that should not have any impact.)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://putco.de/MTMzNDI

**Additional context**
N/A

**Comment by SirStendec** [comment]
Yeah, I've known about this since I implemented the feature. While I'd prefer to have everything Just Work as the user would expect, I ended up determining that it wasn't worth the effort to try fixing Twitch's state when a theme is disabled.

I'd have to get inventive to store Twitch's native dark mode setting when FFZ isn't doing its thing, and... well, it's not worth it. You can just toggle the theme if you stop using FFZ's theme stuff. The UI is messed up, but it still works perfectly fine. I just don't think it's worth the development work to fix it.

Someone else is fine to try tackling it, but I won't be spending time on it unless something changes.

**Comment by Marenthyu** [comment]
Alright, sounds fair enough!

Hope it wasn't a duplicate submission, i did search older issues before submitting.

Thanks for the work you do!
