### ISSUE TITLE
Twitch Emotes in Emote Menu Not Sorted

### ISSUE THREAD

**Issue by DS1337** [FrankerFaceZ/FrankerFaceZ#714]
Hello,

Sry 4 my bad english! :S

like 1 week now, my following channels on the left side, are not expanded and i must always selft open it!
How to change this ore set it up?

And ne Global Twitch Emotes are no more sorted by "time"
So, from old -> new like always..
But now all emotes are mixed and I cant find a way to sort it like original...

**Comment by SirStendec** [comment]
The left side-bar is a Twitch experiment. We do not support Twitch experiments as a general rule.

Emote sorting was broken because we can no longer treat emote IDs as numbers. The IDs of the new bits reward emotes are not numbers. That being said I can put in a special case for sorting, so I'll probably do that soon.

**Comment by DS1337** [comment]
Sounds good buddy! :)
Hope the old sorting will come back again ;D


And the problem with the sidebar i got solved!
Just clear cache and cookies from twitch.tv and its working again ^^
