### ISSUE TITLE
Fix backticks in chat

### ISSUE THREAD

**Issue by tbodt** [FrankerFaceZ/FrankerFaceZ#718]
**Is your feature request related to a problem? Please describe.**
The new Twitch font has a broken backtick character. It seems to have zero width, so it appears on top of the character that comes after it.

**Describe the solution you'd like**
Perhaps inserting `<span style="width: 1ex"></span>` or something after each backtick in a chat message.

**Describe alternatives you've considered**
Changing the font to Helvetica also works, but I like the new font and would prefer to use that.

**Additional context**
Here's an example. The message actually says `\`test\``.
<img width="131" alt="image" src="https://user-images.githubusercontent.com/5678977/71701866-1b48ac00-2d81-11ea-9c9a-e17b4878001c.png">

**Comment by SirStendec** [comment]
I'm going to have to draw a line and not implement individual glyph overrides because of Twitch's awful font choice. Sorry. I know some people like the font, but I'm not willing to go that far. Please make sure to send feedback to Twitch about how this causes incorrect display of chat messages, if you have not already.
