### ISSUE TITLE
Stream Delay display missing in FireFox

### ISSUE THREAD

**Issue by GeekBoyMN** [FrankerFaceZ/FrankerFaceZ#749]
I've recently started using FireFox to watch Twitch streams and so far the Stream Latency display below the stream window does not show up. It shows up fine in Chrome but I can't find any settings to make it show up in FireFox. The uptime, viewer count, host button etc are all there but not the stream delay. 

 Most current versions of FireFox, Chrome, FFZ, BTTV and all running on Windows 8.1

**Comment by GeekBoyMN** [comment]
Why was my issue closed?

**Comment by SirStendec** [comment]
1. The issue is tagged invalid. You didn't follow the rules for submitting an issue.
2. I can't reproduce any issues with the stream latency display on Firefox, which means you're probably using another extension which interferes or Twitch is running an experiment on you which  breaks FFZ features. We don't support Twitch experiments.
