### ISSUE TITLE
Playback Speed Not Working on Firefox

### ISSUE THREAD

**Issue by willscottt** [FrankerFaceZ/FrankerFaceZ#763]
**Describe the bug**
The playback speed options do nothing when watching a VOD with FFZ enabled in Firefox

**To Reproduce**
1. Watch any VOD with FFZ enabled
2. Click on 'Settings' > "Speed" > Any playback speed
3. See that playback setting has no effect on VOD speed

**Expected behavior**
The different playback speeds would speed up or slow down the VOD accordingly.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 73.0.1
 - Other Extensions: BetterTTV, UBlock Origin

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://pastebin.com/9tx7NeR8

**Additional context**
Tested the speed settings in Firefox with FFZ disabled and they worked fine, also tested Chrome with FFZ installed and they worked fine,

**Comment by willscottt** [comment]
Any updates on this? Issue is still persisting. Also extra info - the playback speed settings works on clips but still not VODs

**Comment by yuriks** [comment]
fwiw, this seems to be related to the audio compressor: playback speed works ok until it is enabled, and then stops working until the player is refreshed. (That is, if compression is enabled by default it'll never work, otherwise it'll stop working once it is enabled, and keep not working even after disabled, until the stream is refreshed.)

**Comment by SirStendec** [comment]
Assuming your'e using the audio compressor, this is a browser bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1517199) and not something within the scope of the extension to fix. You'll need to disable the audio compressor and reset player to recreate the HTML5 video element before adjusting playbackRate will have an effect.

The reason it would work on clips is because FFZ automatically disables the compressor for clip playback. We do this as due to an oversight on Twitch's part (clip source files don't have CORS headers), enabling the audio compressor for a clip results in no audio playback. As the compressor is not enabled, it isn't causing audio to go through the special media pipeline that's breaking playbackRate.

If you are *not* using the audio compressor, please let me know and I will re-open the issue. Otherwise I'll assume that it's the browser bug that we can't really address.

**Comment by drksx** [comment]
I had been using the compressor, but I tested turning off the audio compressor while it’s enabled in settings, and also by disabling the audio compressor option entirely, and the play rate controls still don't work.

**Comment by drksx** [comment]
Scratch that, after testing and going back to the browser again, now they work.  Very odd.  Thank you.

**Comment by DragRedSim** [comment]
The browser bug has been fixed with the release of Firefox 91. It should now be possible to use playback speed with the audio compressor.
