### ISSUE TITLE
Scrolling doesn't pause

### ISSUE THREAD

**Issue by NRN1337** [FrankerFaceZ/FrankerFaceZ#777]
**Describe the bug**
I wanted to have it on scroll and since that seems to be overridden by FFZ it was on hover but when I put it on hover it pauses for like milisecond and chat just continues. I tried changing the settings but never found how to have scroll as a pause nor how to fix the issue. Don't wanna use a hotkey because I'm basicly laid back on chair while modding and only using my mice for moderation.

Basicly,only want it on scroll as intended by twitch instead of it getting overridden

**To Reproduce**
1. Go to 'FFZ behavior settings'
2. Put it on hover and see or try searching for scroll instead of hover which for some reason doesn't exist. Also when its on "disabled" it doesn't do anything which I assume was somewhat logical but it does say its "Pause Chat Scrolling" - disabled.. Custom,my guess

**Environment (please complete the following information):**
 - OS: Win10x64 Pro 1909
 - Browser: Chrome 
 - Version: 80.0.3987.132 
 - Other Extensions: BTTV,uBlock Origin

**Comment by SirStendec** [comment]
Chat *always* pauses when you scroll up. FrankerFaceZ does not disable that behavior or provide options to disable it. The setting you are talking about is only for configuring how chat reacts to key presses and mouse movement.

If you see `More messages below` at the bottom of chat, that means that scrolling has been temporarily halted because you have scrolled. Same as with vanilla Twitch. If chat still appears to be scrolling when that is visible, it means you've been paused too long and old messages are being removed from memory.

When you are a moderator, that message changes with vanilla Twitch to say `Chat paused due to scroll`. It has exactly the same meaning.

If you are seeing that and chat is still moving, feel free to explain further and I'll re-open this issue, otherwise I will assume that you were merely confused by differences in the UI that have crept in over time.

**Comment by NRN1337** [comment]
I don't see "more messages below" tho. I had to disable FFZ to see it. When FFZ was on as extension,even when I scroll that popup wasn't showing. I tried it on Opera,it worked fine with FFZ but on Chrome,dunno why. I'll reset my settings and give feedback again later. 

Thank you for maintaining the extension <3!
