### ISSUE TITLE
Channel specific filters

### ISSUE THREAD

**Issue by hesoyam5** [FrankerFaceZ/FrankerFaceZ#779]
**Is your feature request related to a problem?**
No.
**Describe the solution you'd like**
Ability to set filters for a certain specific channel. These filters would override global filters completely or work together with global filters but for a certain channel the user has specified - so for example you filter the words "apple" and "banana" globally, and in another channel and only in that channel you want the additional word "lemon" filtered, then the global filters work in tandem with the channel filters and in that specified channel those 3 words are filtered, but in all the other channels only the first 2 words.

**Comment by SirStendec** [comment]
You can already accomplish this by using multiple settings profiles.

1. Only add terms you want to be filtered globally to the Default Profile.
2. Create an additional profile per channel, as needed. When creating the profile, add a rule so that it only runs on the channel you want.
3. With that profile selected (upper-left drop-down in the control center), configure the settings you only want to apply when that profile is active. In this case, you'll add the terms you want to that profile.
