### ISSUE TITLE
Hide offline option is no longer working

### ISSUE THREAD

**Issue by gaekwad** [FrankerFaceZ/FrankerFaceZ#801]
Ever since a few days ago, the "hide offline" option for the followed channels panel no longer seems to do anything.  I'm on Firefox.

**Comment by Makifun** [comment]
I am very certain that it was working fine for me before. It only stopped working for me in Firefox when the feature was removed in 4.19.12. Please bring it back! 👍

**Comment by SirStendec** [comment]
The feature was removed because it no longer functions on the new Twitch layout which is at at least 50% roll-out and that will soon become standard for everyone. Due to changes made to the new layout, the feature cannot be implemented in a trivial fashion as it is now and I don't have the resources to spend implementing a more robust version of the feature.
