### ISSUE TITLE
Audio compressor not working with Brave browser

### ISSUE THREAD

**Issue by NRN1337** [FrankerFaceZ/FrankerFaceZ#802]
Audio compression doesn't seem to work in Brave,tried doing a fresh install (and private mdoe) with no extensions aside from ublock origin and ffz,didn't change a thing. 
Any way to fix this? Tested on Chrome and Opera,seem to be working fine.

**Comment by SirStendec** [comment]
If the browser doesn't support the web audio API then there's nothing I can do about it. The logic in FFZ is very simple, just creating a compressor node and associating it with the video element. All the heavy processing is handled by your browser.

I'm not sure why Brave specifically would be having issues since it's a Chromium fork and Chrome has supported web audio API since 2011. This is a won't fix, though. Every Chromium browser I tested it in, it works. Brave needs to get its act together.

**Comment by NRN1337** [comment]
With newer updates it seemed to be working fine (Brave updates). Hopefully there won't be much trouble with this in future. Thanks for the response regardless.
