### ISSUE TITLE
Followed channels that are listed in the Just Chatting section are hidden.

### ISSUE THREAD

**Issue by knifevsface** [FrankerFaceZ/FrankerFaceZ#880]
**Describe the bug**
Could not find anything in settings regarding this.
Any followed channel that is listed in the Just Chatting section disappears from your "Followed Channels" sidebar and disappears from the main "Following > Overview/Live" tabs

**To Reproduce**
1. Load Twitch
2. Just Chatting channels appear in the Followed Channels sidebar / Followed tab for less than a second then disappear.

**Expected behavior**
Followed live channels to always display.

**Environment**
- Windows 10
- Latest Google Chrome
- Other Extensions:  BetterTTV, DuckDuckGo Privacy Essentials, minerBlock, Ublock Origin 

**FFZ Logs**:
Logs stuck on "Uploading..." - no link 

**Additional context**
The issue stops when disabling FrankerFaceZ extension and refreshing Twitch

**Comment by SirStendec** [comment]
Please verify that you have not blocked the Just Chatting category using the buttons that FrankerFaceZ adds to category pages. (Direct Link: https://www.twitch.tv/directory/game/Just%20Chatting )

Blocking a category hides all channels streaming in that category, including from the sidebar and on your directory following page. This is by design and not a bug.

**Comment by knifevsface** [comment]
That fixed it. Thank you!

I must have blocked the category at some point and then forgot about it. It's been messing with me for a while.

Does the block feature by chance also stop notifications when streamers go live in a blocked category?

**Comment by SirStendec** [comment]
FFZ doesn't currently affect notifications in any way.
