### ISSUE TITLE
Deleted message reason always show "Deleted"

### ISSUE THREAD

**Issue by daviirodrig** [FrankerFaceZ/FrankerFaceZ#882]
**Describe the bug**
When you have deleted messages rendering mode on "detailed" it always shows the reason as "deleted" even if it was a timeout or ban.

**To Reproduce**
1. Have rendering mode of deleted messages set to "Detailed"
2. Go on chat
3. Wait for a timeout or do it yourself
4. See reason in the parentheses

**Expected behavior**
Show the right reason like "10:00 timeout", "Banned"

**Screenshots**
Settings:
![image](https://user-images.githubusercontent.com/30713947/89969224-41460100-dc2c-11ea-9aa8-8b7c1bd52c91.png)
Moderator view:
![image](https://user-images.githubusercontent.com/30713947/89969362-908c3180-dc2c-11ea-9af2-40a7dfeab3f5.png)
FFZ user view:
![image](https://user-images.githubusercontent.com/30713947/89969387-a1d53e00-dc2c-11ea-9d18-58d6f4cdee30.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84.0.4147.105
 - Other Extensions: Just FFZ

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
(Upload button didn't work so I uploaded myself)
https://gist.github.com/daviirodrig/46f885f6a75edfa78fbbfeb7b7602539

**Additional context**
It used to show correctly but after some update (don't know exactly which one) it stopped working

**Comment by JimmyBoyHalpert** [comment]
Any update on this? I know FFZ has had a few updates since this issue was first reported and I'm curious if there are settings I can tweak to make it work again.

**Comment by Bas3213** [comment]
This bug is now 1 year old ( FeelsBirthdayMan ).
On a serious note, can we pls get some info on how likely this'll get solved?
I know this isn't the biggest bug FFZ has but it's a pretty simple feature that I (and others) would like to get working again.

**Comment by Kyle1519** [comment]
I was trying to switch to using only FFZ today as I was using FFZ, BTTV, 7TV, and a channel point collector extension which were all causing my twitch pages to load sluggishly. 
FFZ seemed like it was able to handle everything from all the other extensions but when I disabled them, I realized that FFZ doesn't have the option to show ban/timeout reason/length like 7TV does. 

I've had to reenabled 7TV to get this feature back but it would be nice if this could be fixed in FFZ so that it actually consolidates all the features of al the other extensions into one app. 

This is the only roadblock to FFZ being a perfect replacement for all.... hope it gets fixed soon. 
Until then, I guess I just have to continue using 7TV. 
![7TV-example](https://user-images.githubusercontent.com/36649870/154872554-5a3cb8c3-0772-4b1d-a4f9-d066bdc414b7.png)

**Comment by x9136** [comment]
Need that.

**Comment by krenovut** [comment]
Yeah, would be nice to have this features, or at least know that its not in the plans.

**Comment by daviirodrig** [comment]
fixed by 5956312 
thanks SirStendec
