### ISSUE TITLE
GIF emotes have considerable impact on performance

### ISSUE THREAD

**Issue by Farcrada** [FrankerFaceZ/FrankerFaceZ#896]
**Is your feature request related to a problem? Please describe.**
When a channel gets spammed with a lot of animated emotes - this can happen in all channels as long as there's enough spam, it tends to hog a lot of processing power (pretty much exclusively the CPU) for the decompression of GIFs. This in turn may cause the browser to hang and/or crash on lesser-end systems. On a late 4th generation i7 this impact can reach well over 30% for a single process and if you really stress it (with a spammy enough channel): also crash the browser.

**Describe the solution you'd like**
To mitigate the performance impact GIFs have on /the experience/ I would like to propose a switch to another format. There's really only two options:
- [APNG](https://en.wikipedia.org/wiki/APNG), and;
- [FLIF](https://en.wikipedia.org/wiki/Free_Lossless_Image_Format).

Where FLIF has a neat little poly script which you can load in to a webpage: https://github.com/UprootLabs/poly-flif and APNG being natively supported.

**Describe alternatives you've considered**
- Hiding chat, which disconnects and thus removes the load. But we all know how we think about that.
- Enabling static emotes, but this is pretty much the same as hiding chat.
- Limiting the amount of history messages is a solid middle ground, but if the channel is big enough the requests and thus reserved processing power still get hogged up. And having to switch every time you join a different channel can get to be a pain.
- Storing/playing the GIFs locally per channel at all times, but that still doesn't get around the decompression impact we're ultimately dealing with unless you play them all at once in the background, but that would increase memory footprint to say the least and I don't see how it would be feasable in a real world application where you don't have more than 6GB of RAM.
- And lastly: uploading all GIFs again with better optimization, but if you're gonna upload everything again, might as well convert the existing to something more efficient.

**Additional context**
According to this website: https://ezgif.com/help/alternative-animated-image-formats these two options have the widest range of support among the most common browsers (Chrome, Safari and FireFox)

**Comment by SirStendec** [comment]
Couple notes.

First off, FrankerFaceZ does not actually *have* animated emotes at this time. If we did, I'd use APNG for a proper alpha channel. GIF is a terrible format. You're talking about BetterTTV's emotes. They use GIFs for animated emotes. While we have an add-on for displaying BTTV emotes with FFZ, we don't have control over what file format their CDN distributes.

I have my doubts that the performance issue actually has to do with decoding the file format. Instead, I'm assuming that having to do constant repaints to chat to draw the next frame of the animations are the culprit. I haven't looked into it, and as FrankerFaceZ does not actually use animated emotes, I am not willing to spend the time doing so currently.

If you have any findings about the effect of file format when displaying hundreds of animated images in a Twitch chat like environment, or research detailing the painting load (or lack thereof) I'd be interested in seeing it. Otherwise, I'm not going to worry about anything like this until such time as FrankerFaceZ implements native animated emotes, if we do so.
