### ISSUE TITLE
GIF emote resets animation when the same one is posted in chat

### ISSUE THREAD

**Issue by csrapr** [FrankerFaceZ/FrankerFaceZ#985]
**Describe the bug**
If the chat is spamming a GIF emote (for example, [WAYTOODANK](https://betterttv.com/emotes/5ad22a7096065b6c6bddf7f3)), every time a new WAYTOODANK emote is posted, the gif animation is reset and all we see is the first couple frames of the emote.
This only seems to happen on firefox.

**To Reproduce**
1. Go to a fast moving chat and enable gif emotes
2. Wait for a gif emote to get spammed
3. See error

**Expected behavior**
The full animation of the gif emote should be seen regardless of how many times it gets spammed

**Screenshots**
https://streamable.com/6cyjj6

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox 
 - Version: (latest stable)
 - Other Extensions: Ublock Origin

**Comment by SirStendec** [comment]
It's an issue with how Firefox displays animated images.

FrankerFaceZ displays emote images using a basic `<img>` tag. We aren't doing anything weird or special. Your browser should be able to properly display images in that situation. That it is not is not a bug with FrankerFaceZ, it is a bug with Firefox and outside the scope of what this project can or will fix.

**Comment by csrapr** [comment]
@SirStendec it works fine with the BTTV extension though

**Comment by Marckvdv** [comment]
A quick (and perhaps dirty) way to fix this is by adding emotes using the `srcset` attribute instead of the `src`:
[Example](https://codepen.io/marckvdv/pen/BaYxYGY)

The functionality stays the same on Edge (and I assume Chrome). I would implement it and test it myself but I can't seem to find the browser extension source code, but perhaps I am looking in the wrong places. This solution would also apply to SevenTV/SevenTV#171.
